"use client";

import { ExternalLink, Info, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { toast } from "@/components/ui/toast";
import type { SamlConfigResponse } from "@/client/types.gen";

import { ReadOnlyField } from "./ReadOnlyField";

interface ServiceProviderPanelProps {
  config: SamlConfigResponse | null;
}

export function ServiceProviderPanel({ config }: ServiceProviderPanelProps) {
  const handleExport = () => {
    if (!config) {
      return;
    }

    if (!config.sp_metadata_url) {
      toast.error("Unable to open metadata URL", {
        description: "The metadata URL is not configured yet.",
      });
      return;
    }

    // Keep backend as the single source of truth for SP metadata.
    const opened = window.open(config.sp_metadata_url, "_blank");
    if (!opened) {
      toast.error("Unable to open metadata URL", {
        description: "Please allow pop-ups and try again.",
      });
      return;
    }

    opened.opener = null;
  };

  return (
    <div className="grid gap-6">
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border/50 bg-muted/10 px-4 py-3">
        <div>
          <p className="text-xs font-semibold">Share with your IdP</p>
          <p className="text-[11px] text-muted-foreground">
            Open backend-generated SAML SP metadata in a new tab to import into your identity
            provider.
          </p>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="gap-1.5 shrink-0"
          onClick={handleExport}
          disabled={!config}
        >
          <ExternalLink className="h-3.5 w-3.5" />
          Open metadata URL
        </Button>
      </div>

      {!config && (
        <div className="flex items-start gap-3 rounded-xl border border-border/60 bg-muted/20 px-4 py-3.5">
          <Info className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
          <p className="text-sm leading-relaxed text-muted-foreground">
            Save an Identity Provider configuration first. Service Provider values are generated by
            the backend after creation.
          </p>
        </div>
      )}

      {config && (
        <>
          <div className="flex items-start gap-3 rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3.5">
            <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
            <p className="text-sm leading-relaxed text-amber-400/90">
              Copy these values into your IdP. If your IdP supports metadata import, just paste the{" "}
              <a
                href={config.sp_metadata_url}
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2"
              >
                Metadata URL
              </a>{" "}
              and skip the rest.
            </p>
          </div>

          <div className="grid gap-5 sm:grid-cols-2">
            <ReadOnlyField
              label="Entity ID / Audience URI"
              value={config.sp_entity_id}
              hint="Set as 'Audience URI' or 'SP Entity ID' in your IdP."
            />
            <ReadOnlyField
              label="Assertion Consumer Service (ACS) URL"
              value={config.sp_acs_url}
              hint="The SAML callback endpoint your IdP redirects to."
            />
            <ReadOnlyField
              label="Metadata URL"
              value={config.sp_metadata_url}
              hint="Import in your IdP to auto-fill all SP fields at once."
            />
            <ReadOnlyField
              label="Single Logout (SLO) URL"
              value={config.sp_slo_url}
              hint="Optional - enables IdP-initiated global logout."
            />
          </div>

          <Separator />

          <ReadOnlyField
            label="SP Signing Certificate (PEM)"
            value={config.sp_certificate}
            hint="Paste into your IdP so it can verify signed AuthnRequests from RUNE."
            multiline
          />

          <a
            href={config.sp_metadata_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs font-medium text-accent hover:underline"
          >
            <ExternalLink className="h-3 w-3" />
            Open metadata XML in browser
          </a>
        </>
      )}
    </div>
  );
}
