name: Feature Request
description: Suggest a new feature or capability
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand your idea by filling out the sections below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Describe the feature you'd like in a couple of sentences.
      placeholder: e.g. Add support for scheduling workflows with cron expressions.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve? What are you trying to accomplish?
      placeholder: |
        I'm always frustrated when...
        I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I searched existing issues and discussions to avoid duplicates.
          required: true
        - label: I am willing to help implement or test this feature.
