// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://services` | (string & {});
};

/**
 * AdminPasswordResetResponse
 */
export type AdminPasswordResetResponse = {
    /**
     * Temporary Password
     *
     * Temporary password for the user to use
     */
    temporary_password: string;
    /**
     * User Id
     *
     * ID of the user whose password was reset
     */
    user_id: number;
};

/**
 * AdminUserUpdate
 */
export type AdminUserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ApiResponse[AdminPasswordResetResponse]
 */
export type ApiResponseAdminPasswordResetResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: AdminPasswordResetResponse;
};

/**
 * ApiResponse[BulkOperationResult]
 */
export type ApiResponseBulkOperationResult = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: BulkOperationResult;
};

/**
 * ApiResponse[CreateUserResponse]
 */
export type ApiResponseCreateUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CreateUserResponse;
};

/**
 * ApiResponse[CredentialResponse]
 */
export type ApiResponseCredentialResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CredentialResponse;
};

/**
 * ApiResponse[CredentialShareInfo]
 */
export type ApiResponseCredentialShareInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CredentialShareInfo;
};

/**
 * ApiResponse[FirstAdminSignupResponse]
 */
export type ApiResponseFirstAdminSignupResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: FirstAdminSignupResponse;
};

/**
 * ApiResponse[List[TemplateSummary]]
 */
export type ApiResponseListTemplateSummary = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<TemplateSummary>;
};

/**
 * ApiResponse[NoneType]
 */
export type ApiResponseNoneType = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: null;
};

/**
 * ApiResponse[SAMLConfigResponse]
 */
export type ApiResponseSamlConfigResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: SamlConfigResponse;
};

/**
 * ApiResponse[SAMLDiscoverResponse]
 */
export type ApiResponseSamlDiscoverResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: SamlDiscoverResponse;
};

/**
 * ApiResponse[SAMLExchangeResponse]
 */
export type ApiResponseSamlExchangeResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: SamlExchangeResponse;
};

/**
 * ApiResponse[TemplateDetail]
 */
export type ApiResponseTemplateDetail = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TemplateDetail;
};

/**
 * ApiResponse[TemplateWorkflowData]
 */
export type ApiResponseTemplateWorkflowData = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TemplateWorkflowData;
};

/**
 * ApiResponse[TokenResponse]
 */
export type ApiResponseTokenResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TokenResponse;
};

/**
 * ApiResponse[UserResponse]
 */
export type ApiResponseUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: UserResponse;
};

/**
 * ApiResponse[WorkflowDetailDocs]
 */
export type ApiResponseWorkflowDetailDocs = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowDetailDocs;
};

/**
 * ApiResponse[WorkflowDetail]
 */
export type ApiResponseWorkflowDetail = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowDetail;
};

/**
 * ApiResponse[WorkflowPermissionListResponse]
 */
export type ApiResponseWorkflowPermissionListResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowPermissionListResponse;
};

/**
 * ApiResponse[WorkflowShareResponse]
 */
export type ApiResponseWorkflowShareResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowShareResponse;
};

/**
 * ApiResponse[WorkflowVersionConflict]
 */
export type ApiResponseWorkflowVersionConflict = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowVersionConflict;
};

/**
 * ApiResponse[WorkflowVersionDetail]
 */
export type ApiResponseWorkflowVersionDetail = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowVersionDetail;
};

/**
 * ApiResponse[bool]
 */
export type ApiResponseBool = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: boolean;
};

/**
 * ApiResponse[list[CredentialResponseDropDown]]
 */
export type ApiResponseListCredentialResponseDropDown = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialResponseDropDown>;
};

/**
 * ApiResponse[list[CredentialResponse]]
 */
export type ApiResponseListCredentialResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialResponse>;
};

/**
 * ApiResponse[list[CredentialShareInfo]]
 */
export type ApiResponseListCredentialShareInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialShareInfo>;
};

/**
 * ApiResponse[list[CredentialUsage]]
 */
export type ApiResponseListCredentialUsage = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialUsage>;
};

/**
 * ApiResponse[list[ExecutionListItem]]
 */
export type ApiResponseListExecutionListItem = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<ExecutionListItem>;
};

/**
 * ApiResponse[list[UserBasicInfo]]
 */
export type ApiResponseListUserBasicInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<UserBasicInfo>;
};

/**
 * ApiResponse[list[UserResponse]]
 */
export type ApiResponseListUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<UserResponse>;
};

/**
 * ApiResponse[list[WorkflowListItem]]
 */
export type ApiResponseListWorkflowListItem = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<WorkflowListItem>;
};

/**
 * ApiResponse[list[WorkflowVersionListItem]]
 */
export type ApiResponseListWorkflowVersionListItem = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<WorkflowVersionListItem>;
};

/**
 * ApiResponse[str]
 */
export type ApiResponseStr = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: string;
};

/**
 * Body_assertion_consumer_service_auth_saml_acs_post
 */
export type BodyAssertionConsumerServiceAuthSamlAcsPost = {
    /**
     * Samlresponse
     */
    SAMLResponse: string;
    /**
     * Relaystate
     */
    RelayState?: string;
};

/**
 * BulkOperationResult
 *
 * Full result returned by the bulk-workflow endpoint.
 */
export type BulkOperationResult = {
    /**
     * Action
     */
    action: string;
    /**
     * Succeeded
     */
    succeeded: Array<number>;
    /**
     * Failed
     */
    failed: Array<BulkWorkflowFailure>;
    summary: BulkOperationSummary;
    /**
     * Exported
     */
    exported?: Array<WorkflowDetail> | null;
    /**
     * Executions
     */
    executions?: {
        [key: string]: string;
    } | null;
};

/**
 * BulkOperationSummary
 *
 * Aggregate counts for a completed bulk operation.
 */
export type BulkOperationSummary = {
    /**
     * Total
     */
    total: number;
    /**
     * Succeeded
     */
    succeeded: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * BulkWorkflowAction
 *
 * Actions that can be applied to multiple workflows at once.
 */
export type BulkWorkflowAction = 'delete' | 'activate' | 'deactivate' | 'export' | 'run';

/**
 * BulkWorkflowFailure
 *
 * A single workflow that could not be processed in a bulk operation.
 */
export type BulkWorkflowFailure = {
    /**
     * Id
     */
    id: number;
    /**
     * Reason
     */
    reason: string;
};

/**
 * BulkWorkflowRequest
 *
 * Request body for the bulk-workflow endpoint.
 */
export type BulkWorkflowRequest = {
    /**
     * Workflow Ids
     *
     * IDs of the workflows to operate on (1–100 items; duplicates are ignored).
     */
    workflow_ids: Array<number>;
    action: BulkWorkflowAction;
};

/**
 * ClearThreadResponse
 *
 * Response body for clearing a thread.
 */
export type ClearThreadResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Newly created user
     */
    user: UserResponse;
    /**
     * Temporary Password
     *
     * Temporary password for the user to use on first login
     */
    temporary_password: string;
};

/**
 * CredentialCreate
 *
 * Schema for creating a new credential.
 */
export type CredentialCreate = {
    /**
     * Name
     *
     * Credential name
     */
    name: string;
    /**
     * Type of credential
     */
    credential_type: CredentialType;
    /**
     * Credential Data
     *
     * Credential data (will be encrypted)
     */
    credential_data?: {
        [key: string]: unknown;
    };
};

/**
 * CredentialResponse
 *
 * Schema for credential response (without sensitive data).
 */
export type CredentialResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    credential_type: CredentialType;
    /**
     * Created By
     */
    created_by: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Is Owner
     *
     * Whether current user is the owner of this credential
     */
    is_owner?: boolean;
    /**
     * Can Share
     *
     * Whether current user can share this credential
     */
    can_share?: boolean;
    /**
     * Can Edit
     *
     * Whether current user can edit this credential
     */
    can_edit?: boolean;
    /**
     * Can Delete
     *
     * Whether current user can delete this credential
     */
    can_delete?: boolean;
};

/**
 * CredentialResponseDropDown
 *
 * Schema for credential response in dropdowns.
 */
export type CredentialResponseDropDown = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    credential_type: CredentialType;
};

/**
 * CredentialShare
 *
 * Schema for sharing a credential with a user.
 */
export type CredentialShare = {
    /**
     * User Id
     *
     * ID of user to share with
     */
    user_id: number;
};

/**
 * CredentialShareInfo
 *
 * Information about a credential share.
 */
export type CredentialShareInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * User Email
     */
    user_email: string;
    /**
     * User Name
     */
    user_name: string;
    /**
     * Shared At
     */
    shared_at: string;
    /**
     * Shared By
     */
    shared_by: number | null;
    /**
     * Shared By Name
     *
     * Name of the user who shared this credential
     */
    shared_by_name?: string | null;
};

/**
 * CredentialType
 *
 * Credential type enumeration.
 */
export type CredentialType = 'api_key' | 'oauth2' | 'basic_auth' | 'header' | 'token' | 'custom' | 'smtp';

/**
 * CredentialUpdate
 *
 * Schema for updating a credential.
 */
export type CredentialUpdate = {
    /**
     * Name
     *
     * Credential name
     */
    name?: string | null;
    /**
     * Type of credential
     */
    credential_type?: CredentialType | null;
    /**
     * Credential Data
     *
     * Credential data (will be encrypted)
     */
    credential_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CredentialUsage
 *
 * Schema for reporting workflow usage of a credential.
 */
export type CredentialUsage = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * ExecutionListItem
 */
export type ExecutionListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Id
     */
    workflow_id: number;
    /**
     * Workflow Name
     */
    workflow_name: string;
    status: ExecutionStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Total Duration Ms
     */
    total_duration_ms?: number | null;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
};

/**
 * ExecutionStatus
 *
 * Execution status enumeration.
 */
export type ExecutionStatus = 'pending' | 'completed' | 'failed' | 'halted';

/**
 * FirstAdminSignupRequest
 *
 * Request schema for first-time admin account creation.
 */
export type FirstAdminSignupRequest = {
    /**
     * Name
     *
     * Admin's full name
     */
    name: string;
    /**
     * Email
     *
     * Admin's email address
     */
    email: string;
    /**
     * Password
     *
     * Admin's password
     */
    password: string;
};

/**
 * FirstAdminSignupResponse
 *
 * Response schema for successful first-time admin signup.
 */
export type FirstAdminSignupResponse = {
    /**
     * User Id
     *
     * ID of the newly created admin user
     */
    user_id: number;
    /**
     * Name
     *
     * Admin's name
     */
    name: string;
    /**
     * Email
     *
     * Admin's email
     */
    email: string;
};

/**
 * GenerateWorkflowDocsRequest
 */
export type GenerateWorkflowDocsRequest = {
    /**
     * Target Audience
     */
    target_audience?: 'Technical Developer' | 'Executive Summary';
};

/**
 * GenerateWorkflowRequest
 *
 * Request body for creating a workflow from natural language.
 */
export type GenerateWorkflowRequest = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     *
     * User's email address
     */
    email: string;
    /**
     * Password
     *
     * User's password
     */
    password: string;
};

/**
 * ProfileUpdate
 */
export type ProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     *
     * Valid refresh token
     */
    refresh_token: string;
};

/**
 * SAMLConfigCreate
 *
 * Request body for ``POST /auth/saml/config``.
 */
export type SamlConfigCreate = {
    /**
     * Name
     *
     * Display name, e.g. 'Okta' or 'Azure AD'
     */
    name: string;
    /**
     * Idp Entity Id
     *
     * IdP Entity ID from their metadata XML
     */
    idp_entity_id: string;
    /**
     * Idp Sso Url
     *
     * IdP SSO redirect-binding URL (must be http/https)
     */
    idp_sso_url: string;
    /**
     * Idp Slo Url
     *
     * IdP Single Logout URL (optional, must be http/https)
     */
    idp_slo_url?: string | null;
    /**
     * Idp Certificate
     *
     * IdP X.509 signing certificate — full PEM including BEGIN/END headers
     */
    idp_certificate: string;
    /**
     * Domain Hint
     *
     * Email domain for SSO auto-discovery, e.g. 'acme.com'
     */
    domain_hint?: string | null;
};

/**
 * SAMLConfigResponse
 *
 * Admin-facing response for a SAML configuration.
 *
 * Includes all IdP fields plus computed SP fields that admins need to paste
 * into their IdP when setting up the integration.  The SP private key is
 * intentionally excluded.
 */
export type SamlConfigResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Idp Entity Id
     */
    idp_entity_id: string;
    /**
     * Idp Sso Url
     */
    idp_sso_url: string;
    /**
     * Idp Slo Url
     */
    idp_slo_url?: string | null;
    /**
     * Sp Certificate
     *
     * SP X.509 certificate PEM – paste into your IdP
     */
    sp_certificate: string;
    /**
     * Sp Entity Id
     *
     * SP Entity ID / Audience URI to enter in your IdP
     */
    sp_entity_id: string;
    /**
     * Sp Acs Url
     *
     * Assertion Consumer Service URL to enter in your IdP
     */
    sp_acs_url: string;
    /**
     * Sp Metadata Url
     *
     * Public URL of this SP's metadata XML – paste into your IdP to auto-configure
     */
    sp_metadata_url: string;
    /**
     * Sp Slo Url
     *
     * Single Logout URL to configure in your IdP (optional)
     */
    sp_slo_url: string;
    /**
     * Domain Hint
     */
    domain_hint?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * SAMLConfigUpdate
 *
 * Request body for ``PUT /auth/saml/config``.
 */
export type SamlConfigUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Idp Entity Id
     */
    idp_entity_id?: string | null;
    /**
     * Idp Sso Url
     */
    idp_sso_url?: string | null;
    /**
     * Idp Slo Url
     */
    idp_slo_url?: string | null;
    /**
     * Idp Certificate
     */
    idp_certificate?: string | null;
    /**
     * Domain Hint
     */
    domain_hint?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * SAMLDiscoverResponse
 *
 * Response for ``GET /auth/saml/discover``.
 *
 * Intentionally does **not** expose internal IDs — the single-IdP model
 * means the login endpoint is always ``/auth/saml/login`` regardless.
 */
export type SamlDiscoverResponse = {
    /**
     * Found
     *
     * Whether an active SAML config exists for this email domain
     */
    found: boolean;
    /**
     * Login Url
     *
     * SSO initiation URL to redirect the user to, if found
     */
    login_url?: string | null;
};

/**
 * SAMLExchangeRequest
 *
 * Request body for ``POST /auth/saml/exchange``.
 */
export type SamlExchangeRequest = {
    /**
     * Code
     *
     * One-time SSO exchange code received as a URL query parameter after IdP redirect
     */
    code: string;
};

/**
 * SAMLExchangeResponse
 *
 * Response body for ``POST /auth/saml/exchange``.
 *
 * The access token is delivered as an ``HttpOnly`` cookie on the same
 * response — it never appears in this JSON body.
 */
export type SamlExchangeResponse = {
    /**
     * Refresh Token
     *
     * Long-lived refresh token — store in localStorage
     */
    refresh_token: string;
    /**
     * Expires In
     *
     * Access token lifetime in seconds
     */
    expires_in: number;
};

/**
 * TemplateCreate
 *
 * Schema for creating a new template.
 */
export type TemplateCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Category
     */
    category?: string;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Is Public
     */
    is_public?: boolean;
};

/**
 * TemplateDetail
 *
 * Detailed template information including workflow data.
 */
export type TemplateDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Category
     */
    category: string;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Usage Count
     */
    usage_count: number;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Created By
     */
    created_by: number | null;
};

/**
 * TemplateSummary
 *
 * Template summary for listing templates.
 */
export type TemplateSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Category
     */
    category: string;
    /**
     * Usage Count
     */
    usage_count: number;
    /**
     * Is Public
     */
    is_public: boolean;
};

/**
 * TemplateWorkflowData
 *
 * Schema for template workflow data response.
 */
export type TemplateWorkflowData = {
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     *
     * JWT access token
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Refresh token for obtaining new access tokens
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type, always 'bearer'
     */
    token_type?: string;
    /**
     * Expires In
     *
     * Access token expiration time in seconds
     */
    expires_in: number;
};

/**
 * UserBasicInfo
 *
 * Minimal user info for sharing purposes.
 */
export type UserBasicInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    role: UserRole;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * User role: 'user' or 'admin'
     */
    role?: UserRole;
};

/**
 * UserPasswordChange
 */
export type UserPasswordChange = {
    /**
     * Old Password
     *
     * Current password for verification
     */
    old_password: string;
    /**
     * New Password
     *
     * New password
     */
    new_password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    role: UserRole;
    /**
     * Is Active
     *
     * Account active status
     */
    is_active: boolean;
    /**
     * Created At
     *
     * Account creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
    /**
     * Last Login At
     *
     * Last login timestamp
     */
    last_login_at?: string | null;
    /**
     * Must Change Password
     *
     * Flag indicating user must change password
     */
    must_change_password: boolean;
};

/**
 * UserRole
 *
 * User role enumeration.
 */
export type UserRole = 'user' | 'admin';

/**
 * UserStatusUpdate
 */
export type UserStatusUpdate = {
    /**
     * Is Active
     *
     * Set to true to activate, false to deactivate
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowCreate
 */
export type WorkflowCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * WorkflowCreateVersion
 */
export type WorkflowCreateVersion = {
    /**
     * Base Version Id
     *
     * Expected current latest version id. Null is allowed only for the first save.
     */
    base_version_id?: number | null;
    /**
     * Workflow Data
     *
     * Workflow definition to save
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Message
     *
     * Revision message
     */
    message?: string | null;
};

/**
 * WorkflowDetail
 */
export type WorkflowDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    latest_version?: WorkflowVersionDetail | null;
    /**
     * Published Version Id
     */
    published_version_id?: number | null;
    /**
     * Has Unpublished Changes
     */
    has_unpublished_changes: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowDetailDocs
 */
export type WorkflowDetailDocs = {
    /**
     * Docs
     */
    docs: string;
};

/**
 * WorkflowListItem
 */
export type WorkflowListItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    role: WorkflowRole;
};

/**
 * WorkflowPermissionInfo
 *
 * Information about a user's permission on a workflow.
 */
export type WorkflowPermissionInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * User Email
     */
    user_email: string;
    /**
     * User Name
     */
    user_name: string;
    role: WorkflowRole;
    user_role: UserRole;
    /**
     * Granted At
     */
    granted_at: string;
    /**
     * Granted By
     */
    granted_by?: number | null;
};

/**
 * WorkflowPermissionListResponse
 *
 * List of all users with access to a workflow.
 */
export type WorkflowPermissionListResponse = {
    /**
     * Workflow Id
     */
    workflow_id: number;
    /**
     * Permissions
     */
    permissions: Array<WorkflowPermissionInfo>;
};

/**
 * WorkflowPublishVersion
 */
export type WorkflowPublishVersion = {
    /**
     * Version Id
     */
    version_id: number;
};

/**
 * WorkflowRestoreVersion
 */
export type WorkflowRestoreVersion = {
    /**
     * Message
     *
     * Revision message
     */
    message?: string | null;
};

/**
 * WorkflowRole
 *
 * Workflow role enumeration.
 */
export type WorkflowRole = 'viewer' | 'editor' | 'owner';

/**
 * WorkflowRoleUpdateRequest
 *
 * Request to update a user's role on a workflow.
 */
export type WorkflowRoleUpdateRequest = {
    /**
     * New role to assign (EDITOR or VIEWER, not OWNER)
     */
    role: WorkflowRole;
};

/**
 * WorkflowRunRequest
 */
export type WorkflowRunRequest = {
    /**
     * Version Id
     *
     * Specific workflow version to run. Defaults to the published version.
     */
    version_id?: number | null;
};

/**
 * WorkflowShareRequest
 *
 * Request to share a workflow with another user.
 */
export type WorkflowShareRequest = {
    /**
     * User Id
     *
     * ID of the user to share with
     */
    user_id: number;
    /**
     * Role to grant (EDITOR or VIEWER, not OWNER)
     */
    role: WorkflowRole;
};

/**
 * WorkflowShareResponse
 *
 * Response after sharing a workflow.
 */
export type WorkflowShareResponse = {
    /**
     * Status
     */
    status?: string;
    /**
     * Message
     */
    message: string;
};

/**
 * WorkflowUpdateName
 */
export type WorkflowUpdateName = {
    /**
     * Name
     */
    name: string;
};

/**
 * WorkflowUpdateStatus
 */
export type WorkflowUpdateStatus = {
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * WorkflowVersionConflict
 */
export type WorkflowVersionConflict = {
    /**
     * Server Version
     */
    server_version: number;
    /**
     * Server Version Id
     */
    server_version_id: number;
};

/**
 * WorkflowVersionCreator
 */
export type WorkflowVersionCreator = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * WorkflowVersionDetail
 */
export type WorkflowVersionDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Version
     */
    version: number;
    /**
     * Created At
     */
    created_at: string;
    created_by?: WorkflowVersionCreator | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Is Published
     */
    is_published: boolean;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowVersionListItem
 */
export type WorkflowVersionListItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Version
     */
    version: number;
    /**
     * Created At
     */
    created_at: string;
    created_by?: WorkflowVersionCreator | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Is Published
     */
    is_published: boolean;
};

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type RefreshAuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAuthRefreshPostError = RefreshAuthRefreshPostErrors[keyof RefreshAuthRefreshPostErrors];

export type RefreshAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTokenResponse;
};

export type RefreshAuthRefreshPostResponse = RefreshAuthRefreshPostResponses[keyof RefreshAuthRefreshPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type SpMetadataAuthSamlMetadataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/saml/metadata';
};

export type SpMetadataAuthSamlMetadataGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SamlLoginAuthSamlLoginGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Redirect
         */
        redirect?: string | null;
    };
    url: '/auth/saml/login';
};

export type SamlLoginAuthSamlLoginGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SamlLoginAuthSamlLoginGetError = SamlLoginAuthSamlLoginGetErrors[keyof SamlLoginAuthSamlLoginGetErrors];

export type DiscoverAuthSamlDiscoverGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/auth/saml/discover';
};

export type DiscoverAuthSamlDiscoverGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscoverAuthSamlDiscoverGetError = DiscoverAuthSamlDiscoverGetErrors[keyof DiscoverAuthSamlDiscoverGetErrors];

export type DiscoverAuthSamlDiscoverGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseSamlDiscoverResponse;
};

export type DiscoverAuthSamlDiscoverGetResponse = DiscoverAuthSamlDiscoverGetResponses[keyof DiscoverAuthSamlDiscoverGetResponses];

export type AssertionConsumerServiceAuthSamlAcsPostData = {
    body: BodyAssertionConsumerServiceAuthSamlAcsPost;
    path?: never;
    query?: never;
    url: '/auth/saml/acs';
};

export type AssertionConsumerServiceAuthSamlAcsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssertionConsumerServiceAuthSamlAcsPostError = AssertionConsumerServiceAuthSamlAcsPostErrors[keyof AssertionConsumerServiceAuthSamlAcsPostErrors];

export type SingleLogoutAuthSamlSloGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Samlrequest
         */
        SAMLRequest?: string | null;
        /**
         * Sigalg
         */
        SigAlg?: string | null;
        /**
         * Signature
         */
        Signature?: string | null;
        /**
         * Relaystate
         */
        RelayState?: string;
    };
    url: '/auth/saml/slo';
};

export type SingleLogoutAuthSamlSloGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SingleLogoutAuthSamlSloGetError = SingleLogoutAuthSamlSloGetErrors[keyof SingleLogoutAuthSamlSloGetErrors];

export type ExchangeSsoCodeAuthSamlExchangePostData = {
    body: SamlExchangeRequest;
    path?: never;
    query?: never;
    url: '/auth/saml/exchange';
};

export type ExchangeSsoCodeAuthSamlExchangePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExchangeSsoCodeAuthSamlExchangePostError = ExchangeSsoCodeAuthSamlExchangePostErrors[keyof ExchangeSsoCodeAuthSamlExchangePostErrors];

export type ExchangeSsoCodeAuthSamlExchangePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseSamlExchangeResponse;
};

export type ExchangeSsoCodeAuthSamlExchangePostResponse = ExchangeSsoCodeAuthSamlExchangePostResponses[keyof ExchangeSsoCodeAuthSamlExchangePostResponses];

export type DeleteSamlConfigAuthSamlConfigDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/saml/config';
};

export type DeleteSamlConfigAuthSamlConfigDeleteResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type DeleteSamlConfigAuthSamlConfigDeleteResponse = DeleteSamlConfigAuthSamlConfigDeleteResponses[keyof DeleteSamlConfigAuthSamlConfigDeleteResponses];

export type GetSamlConfigAuthSamlConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/saml/config';
};

export type GetSamlConfigAuthSamlConfigGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseSamlConfigResponse;
};

export type GetSamlConfigAuthSamlConfigGetResponse = GetSamlConfigAuthSamlConfigGetResponses[keyof GetSamlConfigAuthSamlConfigGetResponses];

export type CreateSamlConfigAuthSamlConfigPostData = {
    body: SamlConfigCreate;
    path?: never;
    query?: never;
    url: '/auth/saml/config';
};

export type CreateSamlConfigAuthSamlConfigPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSamlConfigAuthSamlConfigPostError = CreateSamlConfigAuthSamlConfigPostErrors[keyof CreateSamlConfigAuthSamlConfigPostErrors];

export type CreateSamlConfigAuthSamlConfigPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseSamlConfigResponse;
};

export type CreateSamlConfigAuthSamlConfigPostResponse = CreateSamlConfigAuthSamlConfigPostResponses[keyof CreateSamlConfigAuthSamlConfigPostResponses];

export type UpdateSamlConfigAuthSamlConfigPutData = {
    body: SamlConfigUpdate;
    path?: never;
    query?: never;
    url: '/auth/saml/config';
};

export type UpdateSamlConfigAuthSamlConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSamlConfigAuthSamlConfigPutError = UpdateSamlConfigAuthSamlConfigPutErrors[keyof UpdateSamlConfigAuthSamlConfigPutErrors];

export type UpdateSamlConfigAuthSamlConfigPutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseSamlConfigResponse;
};

export type UpdateSamlConfigAuthSamlConfigPutResponse = UpdateSamlConfigAuthSamlConfigPutResponses[keyof UpdateSamlConfigAuthSamlConfigPutResponses];

export type CheckSetupStatusSetupStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/setup/status';
};

export type CheckSetupStatusSetupStatusGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseBool;
};

export type CheckSetupStatusSetupStatusGetResponse = CheckSetupStatusSetupStatusGetResponses[keyof CheckSetupStatusSetupStatusGetResponses];

export type InitializeFirstAdminSetupInitializePostData = {
    body: FirstAdminSignupRequest;
    path?: never;
    query?: never;
    url: '/setup/initialize';
};

export type InitializeFirstAdminSetupInitializePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitializeFirstAdminSetupInitializePostError = InitializeFirstAdminSetupInitializePostErrors[keyof InitializeFirstAdminSetupInitializePostErrors];

export type InitializeFirstAdminSetupInitializePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseFirstAdminSignupResponse;
};

export type InitializeFirstAdminSetupInitializePostResponse = InitializeFirstAdminSetupInitializePostResponses[keyof InitializeFirstAdminSetupInitializePostResponses];

export type ListWorkflowsWorkflowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workflows/';
};

export type ListWorkflowsWorkflowsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListWorkflowListItem;
};

export type ListWorkflowsWorkflowsGetResponse = ListWorkflowsWorkflowsGetResponses[keyof ListWorkflowsWorkflowsGetResponses];

export type CreateWorkflowWorkflowsPostData = {
    body: WorkflowCreate;
    path?: never;
    query?: never;
    url: '/workflows/';
};

export type CreateWorkflowWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowWorkflowsPostError = CreateWorkflowWorkflowsPostErrors[keyof CreateWorkflowWorkflowsPostErrors];

export type CreateWorkflowWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseWorkflowDetail;
};

export type CreateWorkflowWorkflowsPostResponse = CreateWorkflowWorkflowsPostResponses[keyof CreateWorkflowWorkflowsPostResponses];

export type BulkWorkflowOperationWorkflowsBulkPostData = {
    body: BulkWorkflowRequest;
    path?: never;
    query?: never;
    url: '/workflows/bulk';
};

export type BulkWorkflowOperationWorkflowsBulkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkWorkflowOperationWorkflowsBulkPostError = BulkWorkflowOperationWorkflowsBulkPostErrors[keyof BulkWorkflowOperationWorkflowsBulkPostErrors];

export type BulkWorkflowOperationWorkflowsBulkPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseBulkOperationResult;
};

export type BulkWorkflowOperationWorkflowsBulkPostResponse = BulkWorkflowOperationWorkflowsBulkPostResponses[keyof BulkWorkflowOperationWorkflowsBulkPostResponses];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteError = DeleteWorkflowWorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponse = DeleteWorkflowWorkflowsWorkflowIdDeleteResponses[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteResponses];

export type GetWorkflowWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type GetWorkflowWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowWorkflowsWorkflowIdGetError = GetWorkflowWorkflowsWorkflowIdGetErrors[keyof GetWorkflowWorkflowsWorkflowIdGetErrors];

export type GetWorkflowWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type GetWorkflowWorkflowsWorkflowIdGetResponse = GetWorkflowWorkflowsWorkflowIdGetResponses[keyof GetWorkflowWorkflowsWorkflowIdGetResponses];

export type UpdateStatusWorkflowsWorkflowIdStatusPutData = {
    body: WorkflowUpdateStatus;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/status';
};

export type UpdateStatusWorkflowsWorkflowIdStatusPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStatusWorkflowsWorkflowIdStatusPutError = UpdateStatusWorkflowsWorkflowIdStatusPutErrors[keyof UpdateStatusWorkflowsWorkflowIdStatusPutErrors];

export type UpdateStatusWorkflowsWorkflowIdStatusPutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type UpdateStatusWorkflowsWorkflowIdStatusPutResponse = UpdateStatusWorkflowsWorkflowIdStatusPutResponses[keyof UpdateStatusWorkflowsWorkflowIdStatusPutResponses];

export type UpdateNameWorkflowsWorkflowIdNamePutData = {
    body: WorkflowUpdateName;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/name';
};

export type UpdateNameWorkflowsWorkflowIdNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNameWorkflowsWorkflowIdNamePutError = UpdateNameWorkflowsWorkflowIdNamePutErrors[keyof UpdateNameWorkflowsWorkflowIdNamePutErrors];

export type UpdateNameWorkflowsWorkflowIdNamePutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type UpdateNameWorkflowsWorkflowIdNamePutResponse = UpdateNameWorkflowsWorkflowIdNamePutResponses[keyof UpdateNameWorkflowsWorkflowIdNamePutResponses];

export type ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/versions';
};

export type ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetError = ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetErrors[keyof ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetErrors];

export type ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListWorkflowVersionListItem;
};

export type ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetResponse = ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetResponses[keyof ListWorkflowVersionsWorkflowsWorkflowIdVersionsGetResponses];

export type CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostData = {
    body: WorkflowCreateVersion;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/versions';
};

export type CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostErrors = {
    /**
     * Someone saved a newer workflow version
     */
    409: ApiResponseWorkflowVersionConflict;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostError = CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostErrors[keyof CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostErrors];

export type CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseWorkflowVersionDetail;
};

export type CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostResponse = CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostResponses[keyof CreateWorkflowVersionWorkflowsWorkflowIdVersionsPostResponses];

export type GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetData = {
    body?: never;
    path: {
        /**
         * Version Id
         */
        version_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/versions/{version_id}';
};

export type GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetError = GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetErrors[keyof GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetErrors];

export type GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowVersionDetail;
};

export type GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetResponse = GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetResponses[keyof GetWorkflowVersionWorkflowsWorkflowIdVersionsVersionIdGetResponses];

export type PublishWorkflowVersionWorkflowsWorkflowIdPublishPostData = {
    body: WorkflowPublishVersion;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/publish';
};

export type PublishWorkflowVersionWorkflowsWorkflowIdPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishWorkflowVersionWorkflowsWorkflowIdPublishPostError = PublishWorkflowVersionWorkflowsWorkflowIdPublishPostErrors[keyof PublishWorkflowVersionWorkflowsWorkflowIdPublishPostErrors];

export type PublishWorkflowVersionWorkflowsWorkflowIdPublishPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type PublishWorkflowVersionWorkflowsWorkflowIdPublishPostResponse = PublishWorkflowVersionWorkflowsWorkflowIdPublishPostResponses[keyof PublishWorkflowVersionWorkflowsWorkflowIdPublishPostResponses];

export type RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostData = {
    /**
     * Payload
     */
    body?: WorkflowRestoreVersion | null;
    path: {
        /**
         * Version Id
         */
        version_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/restore/{version_id}';
};

export type RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostError = RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostErrors[keyof RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostErrors];

export type RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseWorkflowVersionDetail;
};

export type RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostResponse = RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostResponses[keyof RestoreWorkflowVersionWorkflowsWorkflowIdRestoreVersionIdPostResponses];

export type RunWorkflowWorkflowsWorkflowIdRunPostData = {
    /**
     * Payload
     */
    body?: WorkflowRunRequest | null;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/run';
};

export type RunWorkflowWorkflowsWorkflowIdRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunWorkflowWorkflowsWorkflowIdRunPostError = RunWorkflowWorkflowsWorkflowIdRunPostErrors[keyof RunWorkflowWorkflowsWorkflowIdRunPostErrors];

export type RunWorkflowWorkflowsWorkflowIdRunPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseStr;
};

export type RunWorkflowWorkflowsWorkflowIdRunPostResponse = RunWorkflowWorkflowsWorkflowIdRunPostResponses[keyof RunWorkflowWorkflowsWorkflowIdRunPostResponses];

export type ListUserExecutionsExecutionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/executions/';
};

export type ListUserExecutionsExecutionsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListExecutionListItem;
};

export type ListUserExecutionsExecutionsGetResponse = ListUserExecutionsExecutionsGetResponses[keyof ListUserExecutionsExecutionsGetResponses];

export type GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/executions/workflows/{workflow_id}';
};

export type GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetError = GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetErrors[keyof GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetErrors];

export type GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetResponse = GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetResponses[keyof GetWorkflowExecutionsExecutionsWorkflowsWorkflowIdGetResponses];

export type GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetData = {
    body?: never;
    path: {
        /**
         * Execution Id
         */
        execution_id: string;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/executions/workflows/{workflow_id}/{execution_id}';
};

export type GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetError = GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetErrors[keyof GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetErrors];

export type GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetResponse = GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetResponses[keyof GetExecutionExecutionsWorkflowsWorkflowIdExecutionIdGetResponses];

export type ShareWorkflowWorkflowsWorkflowIdSharePostData = {
    body: WorkflowShareRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/share';
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostError = ShareWorkflowWorkflowsWorkflowIdSharePostErrors[keyof ShareWorkflowWorkflowsWorkflowIdSharePostErrors];

export type ShareWorkflowWorkflowsWorkflowIdSharePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostResponse = ShareWorkflowWorkflowsWorkflowIdSharePostResponses[keyof ShareWorkflowWorkflowsWorkflowIdSharePostResponses];

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/share/{user_id}';
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteError = RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors[keyof RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors];

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponse = RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses[keyof RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses];

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/permissions';
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetError = ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors[keyof ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors];

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowPermissionListResponse;
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponse = ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses[keyof ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses];

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchData = {
    body: WorkflowRoleUpdateRequest;
    path: {
        /**
         * User Id
         */
        user_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/permissions/{user_id}';
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchError = UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors[keyof UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors];

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponse = UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses[keyof UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses];

export type ListUsersForSharingUsersDirectoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/directory';
};

export type ListUsersForSharingUsersDirectoryGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListUserBasicInfo;
};

export type ListUsersForSharingUsersDirectoryGetResponse = ListUsersForSharingUsersDirectoryGetResponses[keyof ListUsersForSharingUsersDirectoryGetResponses];

export type GetAllUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetAllUsersUsersGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListUserResponse;
};

export type GetAllUsersUsersGetResponse = GetAllUsersUsersGetResponses[keyof GetAllUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCreateUserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type GetUserByIdUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserByIdUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdUsersUserIdGetError = GetUserByIdUsersUserIdGetErrors[keyof GetUserByIdUsersUserIdGetErrors];

export type GetUserByIdUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type GetUserByIdUsersUserIdGetResponse = GetUserByIdUsersUserIdGetResponses[keyof GetUserByIdUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPutData = {
    body: AdminUserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type UpdateUserUsersUserIdPutResponse = UpdateUserUsersUserIdPutResponses[keyof UpdateUserUsersUserIdPutResponses];

export type ResetUserPasswordUsersUserIdPasswordPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/password';
};

export type ResetUserPasswordUsersUserIdPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserPasswordUsersUserIdPasswordPostError = ResetUserPasswordUsersUserIdPasswordPostErrors[keyof ResetUserPasswordUsersUserIdPasswordPostErrors];

export type ResetUserPasswordUsersUserIdPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseAdminPasswordResetResponse;
};

export type ResetUserPasswordUsersUserIdPasswordPostResponse = ResetUserPasswordUsersUserIdPasswordPostResponses[keyof ResetUserPasswordUsersUserIdPasswordPostResponses];

export type SetUserStatusUsersUserIdStatusPatchData = {
    body: UserStatusUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/status';
};

export type SetUserStatusUsersUserIdStatusPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetUserStatusUsersUserIdStatusPatchError = SetUserStatusUsersUserIdStatusPatchErrors[keyof SetUserStatusUsersUserIdStatusPatchErrors];

export type SetUserStatusUsersUserIdStatusPatchResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type SetUserStatusUsersUserIdStatusPatchResponse = SetUserStatusUsersUserIdStatusPatchResponses[keyof SetUserStatusUsersUserIdStatusPatchResponses];

export type GetMyProfileProfileMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile/me';
};

export type GetMyProfileProfileMeGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type GetMyProfileProfileMeGetResponse = GetMyProfileProfileMeGetResponses[keyof GetMyProfileProfileMeGetResponses];

export type UpdateMyProfileProfileMePutData = {
    body: ProfileUpdate;
    path?: never;
    query?: never;
    url: '/profile/me';
};

export type UpdateMyProfileProfileMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileProfileMePutError = UpdateMyProfileProfileMePutErrors[keyof UpdateMyProfileProfileMePutErrors];

export type UpdateMyProfileProfileMePutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type UpdateMyProfileProfileMePutResponse = UpdateMyProfileProfileMePutResponses[keyof UpdateMyProfileProfileMePutResponses];

export type ChangeMyPasswordProfileMePasswordPostData = {
    body: UserPasswordChange;
    path?: never;
    query?: never;
    url: '/profile/me/password';
};

export type ChangeMyPasswordProfileMePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeMyPasswordProfileMePasswordPostError = ChangeMyPasswordProfileMePasswordPostErrors[keyof ChangeMyPasswordProfileMePasswordPostErrors];

export type ChangeMyPasswordProfileMePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type ChangeMyPasswordProfileMePasswordPostResponse = ChangeMyPasswordProfileMePasswordPostResponses[keyof ChangeMyPasswordProfileMePasswordPostResponses];

export type ListTemplatesTemplatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/';
};

export type ListTemplatesTemplatesGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListTemplateSummary;
};

export type ListTemplatesTemplatesGetResponse = ListTemplatesTemplatesGetResponses[keyof ListTemplatesTemplatesGetResponses];

export type CreateTemplateTemplatesPostData = {
    body: TemplateCreate;
    path?: never;
    query?: never;
    url: '/templates/';
};

export type CreateTemplateTemplatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateTemplatesPostError = CreateTemplateTemplatesPostErrors[keyof CreateTemplateTemplatesPostErrors];

export type CreateTemplateTemplatesPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseTemplateDetail;
};

export type CreateTemplateTemplatesPostResponse = CreateTemplateTemplatesPostResponses[keyof CreateTemplateTemplatesPostResponses];

export type DeleteTemplateTemplatesTemplateIdDeleteData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type DeleteTemplateTemplatesTemplateIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateTemplatesTemplateIdDeleteError = DeleteTemplateTemplatesTemplateIdDeleteErrors[keyof DeleteTemplateTemplatesTemplateIdDeleteErrors];

export type DeleteTemplateTemplatesTemplateIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTemplateTemplatesTemplateIdDeleteResponse = DeleteTemplateTemplatesTemplateIdDeleteResponses[keyof DeleteTemplateTemplatesTemplateIdDeleteResponses];

export type GetTemplateTemplatesTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type GetTemplateTemplatesTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateTemplatesTemplateIdGetError = GetTemplateTemplatesTemplateIdGetErrors[keyof GetTemplateTemplatesTemplateIdGetErrors];

export type GetTemplateTemplatesTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTemplateDetail;
};

export type GetTemplateTemplatesTemplateIdGetResponse = GetTemplateTemplatesTemplateIdGetResponses[keyof GetTemplateTemplatesTemplateIdGetResponses];

export type UseTemplateTemplatesTemplateIdUsePostData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}/use';
};

export type UseTemplateTemplatesTemplateIdUsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UseTemplateTemplatesTemplateIdUsePostError = UseTemplateTemplatesTemplateIdUsePostErrors[keyof UseTemplateTemplatesTemplateIdUsePostErrors];

export type UseTemplateTemplatesTemplateIdUsePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTemplateWorkflowData;
};

export type UseTemplateTemplatesTemplateIdUsePostResponse = UseTemplateTemplatesTemplateIdUsePostResponses[keyof UseTemplateTemplatesTemplateIdUsePostResponses];

export type ListCredentialsCredentialsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/credentials/';
};

export type ListCredentialsCredentialsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialResponse;
};

export type ListCredentialsCredentialsGetResponse = ListCredentialsCredentialsGetResponses[keyof ListCredentialsCredentialsGetResponses];

export type CreateCredentialCredentialsPostData = {
    body: CredentialCreate;
    path?: never;
    query?: never;
    url: '/credentials/';
};

export type CreateCredentialCredentialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCredentialCredentialsPostError = CreateCredentialCredentialsPostErrors[keyof CreateCredentialCredentialsPostErrors];

export type CreateCredentialCredentialsPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCredentialResponse;
};

export type CreateCredentialCredentialsPostResponse = CreateCredentialCredentialsPostResponses[keyof CreateCredentialCredentialsPostResponses];

export type ListCredentialsDropdownCredentialsDropdownGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/credentials/dropdown';
};

export type ListCredentialsDropdownCredentialsDropdownGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialResponseDropDown;
};

export type ListCredentialsDropdownCredentialsDropdownGetResponse = ListCredentialsDropdownCredentialsDropdownGetResponses[keyof ListCredentialsDropdownCredentialsDropdownGetResponses];

export type DeleteCredentialCredentialsCredentialIdDeleteData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type DeleteCredentialCredentialsCredentialIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCredentialCredentialsCredentialIdDeleteError = DeleteCredentialCredentialsCredentialIdDeleteErrors[keyof DeleteCredentialCredentialsCredentialIdDeleteErrors];

export type DeleteCredentialCredentialsCredentialIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCredentialCredentialsCredentialIdDeleteResponse = DeleteCredentialCredentialsCredentialIdDeleteResponses[keyof DeleteCredentialCredentialsCredentialIdDeleteResponses];

export type GetCredentialCredentialsCredentialIdGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type GetCredentialCredentialsCredentialIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCredentialCredentialsCredentialIdGetError = GetCredentialCredentialsCredentialIdGetErrors[keyof GetCredentialCredentialsCredentialIdGetErrors];

export type GetCredentialCredentialsCredentialIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialResponse;
};

export type GetCredentialCredentialsCredentialIdGetResponse = GetCredentialCredentialsCredentialIdGetResponses[keyof GetCredentialCredentialsCredentialIdGetResponses];

export type UpdateCredentialCredentialsCredentialIdPatchData = {
    body: CredentialUpdate;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type UpdateCredentialCredentialsCredentialIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCredentialCredentialsCredentialIdPatchError = UpdateCredentialCredentialsCredentialIdPatchErrors[keyof UpdateCredentialCredentialsCredentialIdPatchErrors];

export type UpdateCredentialCredentialsCredentialIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialResponse;
};

export type UpdateCredentialCredentialsCredentialIdPatchResponse = UpdateCredentialCredentialsCredentialIdPatchResponses[keyof UpdateCredentialCredentialsCredentialIdPatchResponses];

export type GetCredentialUsageCredentialsCredentialIdUsageGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/usage';
};

export type GetCredentialUsageCredentialsCredentialIdUsageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCredentialUsageCredentialsCredentialIdUsageGetError = GetCredentialUsageCredentialsCredentialIdUsageGetErrors[keyof GetCredentialUsageCredentialsCredentialIdUsageGetErrors];

export type GetCredentialUsageCredentialsCredentialIdUsageGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialUsage;
};

export type GetCredentialUsageCredentialsCredentialIdUsageGetResponse = GetCredentialUsageCredentialsCredentialIdUsageGetResponses[keyof GetCredentialUsageCredentialsCredentialIdUsageGetResponses];

export type ShareCredentialCredentialsCredentialIdSharePostData = {
    body: CredentialShare;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/share';
};

export type ShareCredentialCredentialsCredentialIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareCredentialCredentialsCredentialIdSharePostError = ShareCredentialCredentialsCredentialIdSharePostErrors[keyof ShareCredentialCredentialsCredentialIdSharePostErrors];

export type ShareCredentialCredentialsCredentialIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCredentialShareInfo;
};

export type ShareCredentialCredentialsCredentialIdSharePostResponse = ShareCredentialCredentialsCredentialIdSharePostResponses[keyof ShareCredentialCredentialsCredentialIdSharePostResponses];

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/share/{user_id}';
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteError = RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors[keyof RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors];

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponse = RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses[keyof RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses];

export type ListCredentialSharesCredentialsCredentialIdSharesGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/shares';
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetError = ListCredentialSharesCredentialsCredentialIdSharesGetErrors[keyof ListCredentialSharesCredentialsCredentialIdSharesGetErrors];

export type ListCredentialSharesCredentialsCredentialIdSharesGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialShareInfo;
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetResponse = ListCredentialSharesCredentialsCredentialIdSharesGetResponses[keyof ListCredentialSharesCredentialsCredentialIdSharesGetResponses];

export type GetMyShareInfoCredentialsCredentialIdMyShareGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/my-share';
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetError = GetMyShareInfoCredentialsCredentialIdMyShareGetErrors[keyof GetMyShareInfoCredentialsCredentialIdMyShareGetErrors];

export type GetMyShareInfoCredentialsCredentialIdMyShareGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialShareInfo;
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetResponse = GetMyShareInfoCredentialsCredentialIdMyShareGetResponses[keyof GetMyShareInfoCredentialsCredentialIdMyShareGetResponses];

export type GenerateWorkflowDocsScrybWorkflowIdPostData = {
    body: GenerateWorkflowDocsRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/scryb/{workflow_id}';
};

export type GenerateWorkflowDocsScrybWorkflowIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateWorkflowDocsScrybWorkflowIdPostError = GenerateWorkflowDocsScrybWorkflowIdPostErrors[keyof GenerateWorkflowDocsScrybWorkflowIdPostErrors];

export type GenerateWorkflowDocsScrybWorkflowIdPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetailDocs;
};

export type GenerateWorkflowDocsScrybWorkflowIdPostResponse = GenerateWorkflowDocsScrybWorkflowIdPostResponses[keyof GenerateWorkflowDocsScrybWorkflowIdPostResponses];

export type ClearThreadSmithWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/smith/{workflow_id}';
};

export type ClearThreadSmithWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearThreadSmithWorkflowIdDeleteError = ClearThreadSmithWorkflowIdDeleteErrors[keyof ClearThreadSmithWorkflowIdDeleteErrors];

export type ClearThreadSmithWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ClearThreadResponse;
};

export type ClearThreadSmithWorkflowIdDeleteResponse = ClearThreadSmithWorkflowIdDeleteResponses[keyof ClearThreadSmithWorkflowIdDeleteResponses];

export type GenerateWorkflowSmithWorkflowIdPostData = {
    body: GenerateWorkflowRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/smith/{workflow_id}';
};

export type GenerateWorkflowSmithWorkflowIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateWorkflowSmithWorkflowIdPostError = GenerateWorkflowSmithWorkflowIdPostErrors[keyof GenerateWorkflowSmithWorkflowIdPostErrors];

export type GenerateWorkflowSmithWorkflowIdPostResponses = {
    /**
     * Server-Sent Events stream with JSON payloads
     */
    200: Blob | File;
};

export type GenerateWorkflowSmithWorkflowIdPostResponse = GenerateWorkflowSmithWorkflowIdPostResponses[keyof GenerateWorkflowSmithWorkflowIdPostResponses];

export type GenerateNewWorkflowSmithPostData = {
    body: GenerateWorkflowRequest;
    path?: never;
    query?: never;
    url: '/smith';
};

export type GenerateNewWorkflowSmithPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateNewWorkflowSmithPostError = GenerateNewWorkflowSmithPostErrors[keyof GenerateNewWorkflowSmithPostErrors];

export type GenerateNewWorkflowSmithPostResponses = {
    /**
     * Server-Sent Events stream with JSON payloads
     */
    200: Blob | File;
};

export type GenerateNewWorkflowSmithPostResponse = GenerateNewWorkflowSmithPostResponses[keyof GenerateNewWorkflowSmithPostResponses];

export type RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostData = {
    body?: never;
    headers?: {
        /**
         * X-Internal-Key
         */
        'x-internal-key'?: string | null;
    };
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/internal/workflows/{workflow_id}/run';
};

export type RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostError = RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostErrors[keyof RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostErrors];

export type RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseStr;
};

export type RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostResponse = RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostResponses[keyof RunWorkflowInternalInternalWorkflowsWorkflowIdRunPostResponses];
