// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://services` | (string & {});
};

/**
 * AdminPasswordResetResponse
 */
export type AdminPasswordResetResponse = {
    /**
     * Temporary Password
     *
     * Temporary password for the user to use
     */
    temporary_password: string;
    /**
     * User Id
     *
     * ID of the user whose password was reset
     */
    user_id: number;
};

/**
 * AdminUserUpdate
 */
export type AdminUserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ApiResponse[AdminPasswordResetResponse]
 */
export type ApiResponseAdminPasswordResetResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: AdminPasswordResetResponse;
};

/**
 * ApiResponse[CreateUserResponse]
 */
export type ApiResponseCreateUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CreateUserResponse;
};

/**
 * ApiResponse[CredentialResponse]
 */
export type ApiResponseCredentialResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CredentialResponse;
};

/**
 * ApiResponse[CredentialShareInfo]
 */
export type ApiResponseCredentialShareInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: CredentialShareInfo;
};

/**
 * ApiResponse[FirstAdminSignupResponse]
 */
export type ApiResponseFirstAdminSignupResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: FirstAdminSignupResponse;
};

/**
 * ApiResponse[FirstTimeSetupStatus]
 */
export type ApiResponseFirstTimeSetupStatus = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: FirstTimeSetupStatus;
};

/**
 * ApiResponse[GeneratedWorkflow]
 */
export type ApiResponseGeneratedWorkflow = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: GeneratedWorkflow;
};

/**
 * ApiResponse[List[TemplateSummary]]
 */
export type ApiResponseListTemplateSummary = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<TemplateSummary>;
};

/**
 * ApiResponse[NoneType]
 */
export type ApiResponseNoneType = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: null;
};

/**
 * ApiResponse[TemplateDetail]
 */
export type ApiResponseTemplateDetail = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TemplateDetail;
};

/**
 * ApiResponse[TemplateWorkflowData]
 */
export type ApiResponseTemplateWorkflowData = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TemplateWorkflowData;
};

/**
 * ApiResponse[TokenResponse]
 */
export type ApiResponseTokenResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: TokenResponse;
};

/**
 * ApiResponse[UserPasswordChangeResponse]
 */
export type ApiResponseUserPasswordChangeResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: UserPasswordChangeResponse;
};

/**
 * ApiResponse[UserResponse]
 */
export type ApiResponseUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: UserResponse;
};

/**
 * ApiResponse[WorkflowDetailDocs]
 */
export type ApiResponseWorkflowDetailDocs = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowDetailDocs;
};

/**
 * ApiResponse[WorkflowDetail]
 */
export type ApiResponseWorkflowDetail = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowDetail;
};

/**
 * ApiResponse[WorkflowPermissionListResponse]
 */
export type ApiResponseWorkflowPermissionListResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowPermissionListResponse;
};

/**
 * ApiResponse[WorkflowShareResponse]
 */
export type ApiResponseWorkflowShareResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Response data
     */
    data: WorkflowShareResponse;
};

/**
 * ApiResponse[list[CredentialResponseDropDown]]
 */
export type ApiResponseListCredentialResponseDropDown = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialResponseDropDown>;
};

/**
 * ApiResponse[list[CredentialResponse]]
 */
export type ApiResponseListCredentialResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialResponse>;
};

/**
 * ApiResponse[list[CredentialShareInfo]]
 */
export type ApiResponseListCredentialShareInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<CredentialShareInfo>;
};

/**
 * ApiResponse[list[UserBasicInfo]]
 */
export type ApiResponseListUserBasicInfo = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<UserBasicInfo>;
};

/**
 * ApiResponse[list[UserResponse]]
 */
export type ApiResponseListUserResponse = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<UserResponse>;
};

/**
 * ApiResponse[list[WorkflowListItem]]
 */
export type ApiResponseListWorkflowListItem = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: Array<WorkflowListItem>;
};

/**
 * ApiResponse[str]
 */
export type ApiResponseStr = {
    /**
     * Success
     *
     * Whether the request was successful
     */
    success?: boolean;
    /**
     * Message
     *
     * Human-readable message
     */
    message?: string;
    /**
     * Data
     *
     * Response data
     */
    data: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Newly created user
     */
    user: UserResponse;
    /**
     * Temporary Password
     *
     * Temporary password for the user to use on first login
     */
    temporary_password: string;
};

/**
 * CredentialCreate
 *
 * Schema for creating a new credential.
 */
export type CredentialCreate = {
    /**
     * Name
     *
     * Credential name
     */
    name: string;
    /**
     * Type of credential
     */
    credential_type: CredentialType;
    /**
     * Credential Data
     *
     * Credential data (will be encrypted)
     */
    credential_data?: {
        [key: string]: unknown;
    };
};

/**
 * CredentialResponse
 *
 * Schema for credential response (without sensitive data).
 */
export type CredentialResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    credential_type: CredentialType;
    /**
     * Created By
     */
    created_by: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Is Owner
     *
     * Whether current user is the owner of this credential
     */
    is_owner?: boolean;
    /**
     * Can Share
     *
     * Whether current user can share this credential
     */
    can_share?: boolean;
    /**
     * Can Edit
     *
     * Whether current user can edit this credential
     */
    can_edit?: boolean;
    /**
     * Can Delete
     *
     * Whether current user can delete this credential
     */
    can_delete?: boolean;
};

/**
 * CredentialResponseDropDown
 *
 * Schema for credential response in dropdowns.
 */
export type CredentialResponseDropDown = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    credential_type: CredentialType;
};

/**
 * CredentialShare
 *
 * Schema for sharing a credential with a user.
 */
export type CredentialShare = {
    /**
     * User Id
     *
     * ID of user to share with
     */
    user_id: number;
};

/**
 * CredentialShareInfo
 *
 * Information about a credential share.
 */
export type CredentialShareInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * User Email
     */
    user_email: string;
    /**
     * User Name
     */
    user_name: string;
    /**
     * Shared At
     */
    shared_at: string;
    /**
     * Shared By
     */
    shared_by: number | null;
    /**
     * Shared By Name
     *
     * Name of the user who shared this credential
     */
    shared_by_name?: string | null;
};

/**
 * CredentialType
 *
 * Credential type enumeration.
 */
export type CredentialType = 'api_key' | 'oauth2' | 'basic_auth' | 'header' | 'token' | 'custom' | 'smtp';

/**
 * CredentialUpdate
 *
 * Schema for updating a credential.
 */
export type CredentialUpdate = {
    /**
     * Name
     *
     * Credential name
     */
    name?: string | null;
    /**
     * Type of credential
     */
    credential_type?: CredentialType | null;
    /**
     * Credential Data
     *
     * Credential data (will be encrypted)
     */
    credential_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * FirstAdminSignupRequest
 *
 * Request schema for first-time admin account creation.
 */
export type FirstAdminSignupRequest = {
    /**
     * Name
     *
     * Admin's full name
     */
    name: string;
    /**
     * Email
     *
     * Admin's email address
     */
    email: string;
    /**
     * Password
     *
     * Admin's password
     */
    password: string;
};

/**
 * FirstAdminSignupResponse
 *
 * Response schema for successful first-time admin signup.
 */
export type FirstAdminSignupResponse = {
    /**
     * User Id
     *
     * ID of the newly created admin user
     */
    user_id: number;
    /**
     * Name
     *
     * Admin's name
     */
    name: string;
    /**
     * Email
     *
     * Admin's email
     */
    email: string;
};

/**
 * FirstTimeSetupStatus
 *
 * Response schema for first-time setup status check.
 */
export type FirstTimeSetupStatus = {
    /**
     * Requires Setup
     *
     * Whether the system requires first-time admin setup
     */
    requires_setup: boolean;
    /**
     * Message
     *
     * Status message
     */
    message: string;
};

/**
 * GenerateWorkflowDocsRequest
 */
export type GenerateWorkflowDocsRequest = {
    /**
     * Target Audience
     */
    target_audience?: 'Technical Developer' | 'Executive Summary';
};

/**
 * GenerateWorkflowRequest
 *
 * Request body for creating a workflow from natural language.
 */
export type GenerateWorkflowRequest = {
    /**
     * Prompt
     */
    prompt: string;
    /**
     * History
     */
    history?: Array<SmithMessage>;
    /**
     * Workflow
     *
     * Optional existing workflow JSON to give the agent full context.
     */
    workflow?: {
        [key: string]: unknown;
    } | null;
    /**
     * Include Trace
     *
     * Include Smith's reasoning/trajectory in the response.
     */
    include_trace?: boolean;
    /**
     * Max Iters
     *
     * Optional override for Smith's ReAct iteration limit.
     */
    max_iters?: number | null;
};

/**
 * GeneratedWorkflow
 *
 * Smith LLM response packaged for the API.
 */
export type GeneratedWorkflow = {
    /**
     * Response
     */
    response: string;
    /**
     * Workflow
     */
    workflow: {
        [key: string]: unknown;
    };
    /**
     * Trace
     *
     * Optional reasoning steps from the agent trajectory.
     */
    trace?: Array<string> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     *
     * User's email address
     */
    email: string;
    /**
     * Password
     *
     * User's password
     */
    password: string;
};

/**
 * ProfileUpdate
 */
export type ProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     *
     * Valid refresh token
     */
    refresh_token: string;
};

/**
 * ScheduleInfo
 *
 * Minimal schedule info for workflow list and detail views.
 */
export type ScheduleInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Start At
     */
    start_at: string;
    /**
     * Next Run At
     */
    next_run_at: string;
    /**
     * Last Run At
     */
    last_run_at: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * SmithMessage
 *
 * Single chat turn used to seed Smith with prior context.
 */
export type SmithMessage = {
    /**
     * Role
     */
    role?: 'user' | 'smith';
    /**
     * Content
     */
    content: string;
};

/**
 * TemplateCreate
 *
 * Schema for creating a new template.
 */
export type TemplateCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Category
     */
    category?: string;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Is Public
     */
    is_public?: boolean;
};

/**
 * TemplateDetail
 *
 * Detailed template information including workflow data.
 */
export type TemplateDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Category
     */
    category: string;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Usage Count
     */
    usage_count: number;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Created By
     */
    created_by: number | null;
};

/**
 * TemplateSummary
 *
 * Template summary for listing templates.
 */
export type TemplateSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Category
     */
    category: string;
    /**
     * Usage Count
     */
    usage_count: number;
    /**
     * Is Public
     */
    is_public: boolean;
};

/**
 * TemplateWorkflowData
 *
 * Schema for template workflow data response.
 */
export type TemplateWorkflowData = {
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     *
     * JWT access token
     */
    access_token: string;
    /**
     * Refresh Token
     *
     * Refresh token for obtaining new access tokens
     */
    refresh_token: string;
    /**
     * Token Type
     *
     * Token type, always 'bearer'
     */
    token_type?: string;
    /**
     * Expires In
     *
     * Access token expiration time in seconds
     */
    expires_in: number;
};

/**
 * TriggerType
 *
 * Workflow trigger type enumeration.
 *
 * Note: ALL workflows can be manually run via API/UI.
 * This enum tracks both automatic and manual trigger types.
 */
export type TriggerType = 'manual' | 'scheduled' | 'webhook';

/**
 * UserBasicInfo
 *
 * Minimal user info for sharing purposes.
 */
export type UserBasicInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * User role: 'user' or 'admin'
     */
    role?: UserRole;
};

/**
 * UserPasswordChange
 */
export type UserPasswordChange = {
    /**
     * Old Password
     *
     * Current password for verification
     */
    old_password: string;
    /**
     * New Password
     *
     * New password
     */
    new_password: string;
};

/**
 * UserPasswordChangeResponse
 */
export type UserPasswordChangeResponse = {
    /**
     * Updated user information
     */
    user: UserResponse;
    /**
     * Access Token
     *
     * New access token with updated must_change_password flag
     */
    access_token: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    role: UserRole;
    /**
     * Is Active
     *
     * Account active status
     */
    is_active: boolean;
    /**
     * Created At
     *
     * Account creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
    /**
     * Last Login At
     *
     * Last login timestamp
     */
    last_login_at?: string | null;
    /**
     * Must Change Password
     *
     * Flag indicating user must change password
     */
    must_change_password: boolean;
};

/**
 * UserRole
 *
 * User role enumeration.
 */
export type UserRole = 'user' | 'admin';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkflowCreate
 */
export type WorkflowCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Workflow Data
     */
    workflow_data?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowDetail
 */
export type WorkflowDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Workflow Data
     */
    workflow_data: {
        [key: string]: unknown;
    };
    /**
     * Version
     */
    version: number;
    trigger_type: TriggerType;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowDetailDocs
 */
export type WorkflowDetailDocs = {
    /**
     * Docs
     */
    docs: string;
};

/**
 * WorkflowListItem
 */
export type WorkflowListItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    trigger_type?: TriggerType;
    schedule?: ScheduleInfo | null;
};

/**
 * WorkflowPermissionInfo
 *
 * Information about a user's permission on a workflow.
 */
export type WorkflowPermissionInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * User Email
     */
    user_email: string;
    /**
     * User Name
     */
    user_name: string;
    role: WorkflowRole;
    /**
     * Granted At
     */
    granted_at: string;
    /**
     * Granted By
     */
    granted_by?: number | null;
};

/**
 * WorkflowPermissionListResponse
 *
 * List of all users with access to a workflow.
 */
export type WorkflowPermissionListResponse = {
    /**
     * Workflow Id
     */
    workflow_id: number;
    /**
     * Permissions
     */
    permissions: Array<WorkflowPermissionInfo>;
};

/**
 * WorkflowRole
 *
 * Workflow role enumeration.
 */
export type WorkflowRole = 'viewer' | 'editor' | 'owner';

/**
 * WorkflowRoleUpdateRequest
 *
 * Request to update a user's role on a workflow.
 */
export type WorkflowRoleUpdateRequest = {
    /**
     * New role to assign (EDITOR or VIEWER, not OWNER)
     */
    role: WorkflowRole;
};

/**
 * WorkflowShareRequest
 *
 * Request to share a workflow with another user.
 */
export type WorkflowShareRequest = {
    /**
     * User Id
     *
     * ID of the user to share with
     */
    user_id: number;
    /**
     * Role to grant (EDITOR or VIEWER, not OWNER)
     */
    role: WorkflowRole;
};

/**
 * WorkflowShareResponse
 *
 * Response after sharing a workflow.
 */
export type WorkflowShareResponse = {
    /**
     * Status
     */
    status?: string;
    /**
     * Message
     */
    message: string;
};

/**
 * WorkflowUpdateData
 */
export type WorkflowUpdateData = {
    /**
     * Workflow Data
     *
     * Updated workflow data
     */
    workflow_data: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowUpdateName
 */
export type WorkflowUpdateName = {
    /**
     * Name
     */
    name: string;
};

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type RefreshAuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAuthRefreshPostError = RefreshAuthRefreshPostErrors[keyof RefreshAuthRefreshPostErrors];

export type RefreshAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTokenResponse;
};

export type RefreshAuthRefreshPostResponse = RefreshAuthRefreshPostResponses[keyof RefreshAuthRefreshPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseNoneType;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type CheckFirstTimeSetupAuthFirstTimeSetupGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/first-time-setup';
};

export type CheckFirstTimeSetupAuthFirstTimeSetupGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseFirstTimeSetupStatus;
};

export type CheckFirstTimeSetupAuthFirstTimeSetupGetResponse = CheckFirstTimeSetupAuthFirstTimeSetupGetResponses[keyof CheckFirstTimeSetupAuthFirstTimeSetupGetResponses];

export type FirstAdminSignupAuthFirstAdminSignupPostData = {
    body: FirstAdminSignupRequest;
    path?: never;
    query?: never;
    url: '/auth/first-admin-signup';
};

export type FirstAdminSignupAuthFirstAdminSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FirstAdminSignupAuthFirstAdminSignupPostError = FirstAdminSignupAuthFirstAdminSignupPostErrors[keyof FirstAdminSignupAuthFirstAdminSignupPostErrors];

export type FirstAdminSignupAuthFirstAdminSignupPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseFirstAdminSignupResponse;
};

export type FirstAdminSignupAuthFirstAdminSignupPostResponse = FirstAdminSignupAuthFirstAdminSignupPostResponses[keyof FirstAdminSignupAuthFirstAdminSignupPostResponses];

export type ListWorkflowsWorkflowsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Schedule
         *
         * Include schedule information for scheduled workflows
         */
        include_schedule?: boolean;
    };
    url: '/workflows/';
};

export type ListWorkflowsWorkflowsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowsWorkflowsGetError = ListWorkflowsWorkflowsGetErrors[keyof ListWorkflowsWorkflowsGetErrors];

export type ListWorkflowsWorkflowsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListWorkflowListItem;
};

export type ListWorkflowsWorkflowsGetResponse = ListWorkflowsWorkflowsGetResponses[keyof ListWorkflowsWorkflowsGetResponses];

export type CreateWorkflowWorkflowsPostData = {
    body: WorkflowCreate;
    path?: never;
    query?: never;
    url: '/workflows/';
};

export type CreateWorkflowWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowWorkflowsPostError = CreateWorkflowWorkflowsPostErrors[keyof CreateWorkflowWorkflowsPostErrors];

export type CreateWorkflowWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseWorkflowDetail;
};

export type CreateWorkflowWorkflowsPostResponse = CreateWorkflowWorkflowsPostResponses[keyof CreateWorkflowWorkflowsPostResponses];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteError = DeleteWorkflowWorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponse = DeleteWorkflowWorkflowsWorkflowIdDeleteResponses[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteResponses];

export type GetWorkflowWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type GetWorkflowWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowWorkflowsWorkflowIdGetError = GetWorkflowWorkflowsWorkflowIdGetErrors[keyof GetWorkflowWorkflowsWorkflowIdGetErrors];

export type GetWorkflowWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type GetWorkflowWorkflowsWorkflowIdGetResponse = GetWorkflowWorkflowsWorkflowIdGetResponses[keyof GetWorkflowWorkflowsWorkflowIdGetResponses];

export type UpdateNameWorkflowsWorkflowIdNamePutData = {
    body: WorkflowUpdateName;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/name';
};

export type UpdateNameWorkflowsWorkflowIdNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNameWorkflowsWorkflowIdNamePutError = UpdateNameWorkflowsWorkflowIdNamePutErrors[keyof UpdateNameWorkflowsWorkflowIdNamePutErrors];

export type UpdateNameWorkflowsWorkflowIdNamePutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type UpdateNameWorkflowsWorkflowIdNamePutResponse = UpdateNameWorkflowsWorkflowIdNamePutResponses[keyof UpdateNameWorkflowsWorkflowIdNamePutResponses];

export type UpdateWorkflowDataWorkflowsWorkflowIdDataPutData = {
    body: WorkflowUpdateData;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/data';
};

export type UpdateWorkflowDataWorkflowsWorkflowIdDataPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowDataWorkflowsWorkflowIdDataPutError = UpdateWorkflowDataWorkflowsWorkflowIdDataPutErrors[keyof UpdateWorkflowDataWorkflowsWorkflowIdDataPutErrors];

export type UpdateWorkflowDataWorkflowsWorkflowIdDataPutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetail;
};

export type UpdateWorkflowDataWorkflowsWorkflowIdDataPutResponse = UpdateWorkflowDataWorkflowsWorkflowIdDataPutResponses[keyof UpdateWorkflowDataWorkflowsWorkflowIdDataPutResponses];

export type RunWorkflowWorkflowsWorkflowIdRunPostData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/run';
};

export type RunWorkflowWorkflowsWorkflowIdRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunWorkflowWorkflowsWorkflowIdRunPostError = RunWorkflowWorkflowsWorkflowIdRunPostErrors[keyof RunWorkflowWorkflowsWorkflowIdRunPostErrors];

export type RunWorkflowWorkflowsWorkflowIdRunPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseStr;
};

export type RunWorkflowWorkflowsWorkflowIdRunPostResponse = RunWorkflowWorkflowsWorkflowIdRunPostResponses[keyof RunWorkflowWorkflowsWorkflowIdRunPostResponses];

export type ShareWorkflowWorkflowsWorkflowIdSharePostData = {
    body: WorkflowShareRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/share';
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostError = ShareWorkflowWorkflowsWorkflowIdSharePostErrors[keyof ShareWorkflowWorkflowsWorkflowIdSharePostErrors];

export type ShareWorkflowWorkflowsWorkflowIdSharePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type ShareWorkflowWorkflowsWorkflowIdSharePostResponse = ShareWorkflowWorkflowsWorkflowIdSharePostResponses[keyof ShareWorkflowWorkflowsWorkflowIdSharePostResponses];

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/share/{user_id}';
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteError = RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors[keyof RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteErrors];

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponse = RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses[keyof RevokeAccessWorkflowsWorkflowIdShareUserIdDeleteResponses];

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/permissions';
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetError = ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors[keyof ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetErrors];

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowPermissionListResponse;
};

export type ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponse = ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses[keyof ListWorkflowPermissionsWorkflowsWorkflowIdPermissionsGetResponses];

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchData = {
    body: WorkflowRoleUpdateRequest;
    path: {
        /**
         * User Id
         */
        user_id: number;
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/permissions/{user_id}';
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchError = UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors[keyof UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchErrors];

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowShareResponse;
};

export type UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponse = UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses[keyof UpdateUserRoleWorkflowsWorkflowIdPermissionsUserIdPatchResponses];

export type ListUsersForSharingUsersSharingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/sharing';
};

export type ListUsersForSharingUsersSharingGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListUserBasicInfo;
};

export type ListUsersForSharingUsersSharingGetResponse = ListUsersForSharingUsersSharingGetResponses[keyof ListUsersForSharingUsersSharingGetResponses];

export type GetAllUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetAllUsersUsersGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListUserResponse;
};

export type GetAllUsersUsersGetResponse = GetAllUsersUsersGetResponses[keyof GetAllUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCreateUserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type GetUserByIdUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserByIdUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdUsersUserIdGetError = GetUserByIdUsersUserIdGetErrors[keyof GetUserByIdUsersUserIdGetErrors];

export type GetUserByIdUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type GetUserByIdUsersUserIdGetResponse = GetUserByIdUsersUserIdGetResponses[keyof GetUserByIdUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPutData = {
    body: AdminUserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type UpdateUserUsersUserIdPutResponse = UpdateUserUsersUserIdPutResponses[keyof UpdateUserUsersUserIdPutResponses];

export type ResetUserPasswordUsersUserIdResetPasswordPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}/reset-password';
};

export type ResetUserPasswordUsersUserIdResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserPasswordUsersUserIdResetPasswordPostError = ResetUserPasswordUsersUserIdResetPasswordPostErrors[keyof ResetUserPasswordUsersUserIdResetPasswordPostErrors];

export type ResetUserPasswordUsersUserIdResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseAdminPasswordResetResponse;
};

export type ResetUserPasswordUsersUserIdResetPasswordPostResponse = ResetUserPasswordUsersUserIdResetPasswordPostResponses[keyof ResetUserPasswordUsersUserIdResetPasswordPostResponses];

export type GetMyProfileProfileMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile/me';
};

export type GetMyProfileProfileMeGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type GetMyProfileProfileMeGetResponse = GetMyProfileProfileMeGetResponses[keyof GetMyProfileProfileMeGetResponses];

export type UpdateMyProfileProfileMePutData = {
    body: ProfileUpdate;
    path?: never;
    query?: never;
    url: '/profile/me';
};

export type UpdateMyProfileProfileMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileProfileMePutError = UpdateMyProfileProfileMePutErrors[keyof UpdateMyProfileProfileMePutErrors];

export type UpdateMyProfileProfileMePutResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserResponse;
};

export type UpdateMyProfileProfileMePutResponse = UpdateMyProfileProfileMePutResponses[keyof UpdateMyProfileProfileMePutResponses];

export type ChangeMyPasswordProfileMeChangePasswordPostData = {
    body: UserPasswordChange;
    path?: never;
    query?: never;
    url: '/profile/me/change-password';
};

export type ChangeMyPasswordProfileMeChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeMyPasswordProfileMeChangePasswordPostError = ChangeMyPasswordProfileMeChangePasswordPostErrors[keyof ChangeMyPasswordProfileMeChangePasswordPostErrors];

export type ChangeMyPasswordProfileMeChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseUserPasswordChangeResponse;
};

export type ChangeMyPasswordProfileMeChangePasswordPostResponse = ChangeMyPasswordProfileMeChangePasswordPostResponses[keyof ChangeMyPasswordProfileMeChangePasswordPostResponses];

export type ListTemplatesTemplatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates/';
};

export type ListTemplatesTemplatesGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListTemplateSummary;
};

export type ListTemplatesTemplatesGetResponse = ListTemplatesTemplatesGetResponses[keyof ListTemplatesTemplatesGetResponses];

export type CreateTemplateTemplatesPostData = {
    body: TemplateCreate;
    path?: never;
    query?: never;
    url: '/templates/';
};

export type CreateTemplateTemplatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateTemplatesPostError = CreateTemplateTemplatesPostErrors[keyof CreateTemplateTemplatesPostErrors];

export type CreateTemplateTemplatesPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseTemplateDetail;
};

export type CreateTemplateTemplatesPostResponse = CreateTemplateTemplatesPostResponses[keyof CreateTemplateTemplatesPostResponses];

export type DeleteTemplateTemplatesTemplateIdDeleteData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type DeleteTemplateTemplatesTemplateIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateTemplatesTemplateIdDeleteError = DeleteTemplateTemplatesTemplateIdDeleteErrors[keyof DeleteTemplateTemplatesTemplateIdDeleteErrors];

export type DeleteTemplateTemplatesTemplateIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTemplateTemplatesTemplateIdDeleteResponse = DeleteTemplateTemplatesTemplateIdDeleteResponses[keyof DeleteTemplateTemplatesTemplateIdDeleteResponses];

export type GetTemplateTemplatesTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}';
};

export type GetTemplateTemplatesTemplateIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateTemplatesTemplateIdGetError = GetTemplateTemplatesTemplateIdGetErrors[keyof GetTemplateTemplatesTemplateIdGetErrors];

export type GetTemplateTemplatesTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTemplateDetail;
};

export type GetTemplateTemplatesTemplateIdGetResponse = GetTemplateTemplatesTemplateIdGetResponses[keyof GetTemplateTemplatesTemplateIdGetResponses];

export type UseTemplateTemplatesTemplateIdUsePostData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/templates/{template_id}/use';
};

export type UseTemplateTemplatesTemplateIdUsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UseTemplateTemplatesTemplateIdUsePostError = UseTemplateTemplatesTemplateIdUsePostErrors[keyof UseTemplateTemplatesTemplateIdUsePostErrors];

export type UseTemplateTemplatesTemplateIdUsePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseTemplateWorkflowData;
};

export type UseTemplateTemplatesTemplateIdUsePostResponse = UseTemplateTemplatesTemplateIdUsePostResponses[keyof UseTemplateTemplatesTemplateIdUsePostResponses];

export type ListCredentialsCredentialsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/credentials/';
};

export type ListCredentialsCredentialsGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialResponse;
};

export type ListCredentialsCredentialsGetResponse = ListCredentialsCredentialsGetResponses[keyof ListCredentialsCredentialsGetResponses];

export type CreateCredentialCredentialsPostData = {
    body: CredentialCreate;
    path?: never;
    query?: never;
    url: '/credentials/';
};

export type CreateCredentialCredentialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCredentialCredentialsPostError = CreateCredentialCredentialsPostErrors[keyof CreateCredentialCredentialsPostErrors];

export type CreateCredentialCredentialsPostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCredentialResponse;
};

export type CreateCredentialCredentialsPostResponse = CreateCredentialCredentialsPostResponses[keyof CreateCredentialCredentialsPostResponses];

export type ListCredentialsDropdownCredentialsDropdownGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/credentials/dropdown';
};

export type ListCredentialsDropdownCredentialsDropdownGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialResponseDropDown;
};

export type ListCredentialsDropdownCredentialsDropdownGetResponse = ListCredentialsDropdownCredentialsDropdownGetResponses[keyof ListCredentialsDropdownCredentialsDropdownGetResponses];

export type DeleteCredentialCredentialsCredentialIdDeleteData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type DeleteCredentialCredentialsCredentialIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCredentialCredentialsCredentialIdDeleteError = DeleteCredentialCredentialsCredentialIdDeleteErrors[keyof DeleteCredentialCredentialsCredentialIdDeleteErrors];

export type DeleteCredentialCredentialsCredentialIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCredentialCredentialsCredentialIdDeleteResponse = DeleteCredentialCredentialsCredentialIdDeleteResponses[keyof DeleteCredentialCredentialsCredentialIdDeleteResponses];

export type GetCredentialCredentialsCredentialIdGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type GetCredentialCredentialsCredentialIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCredentialCredentialsCredentialIdGetError = GetCredentialCredentialsCredentialIdGetErrors[keyof GetCredentialCredentialsCredentialIdGetErrors];

export type GetCredentialCredentialsCredentialIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialResponse;
};

export type GetCredentialCredentialsCredentialIdGetResponse = GetCredentialCredentialsCredentialIdGetResponses[keyof GetCredentialCredentialsCredentialIdGetResponses];

export type UpdateCredentialCredentialsCredentialIdPatchData = {
    body: CredentialUpdate;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}';
};

export type UpdateCredentialCredentialsCredentialIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCredentialCredentialsCredentialIdPatchError = UpdateCredentialCredentialsCredentialIdPatchErrors[keyof UpdateCredentialCredentialsCredentialIdPatchErrors];

export type UpdateCredentialCredentialsCredentialIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialResponse;
};

export type UpdateCredentialCredentialsCredentialIdPatchResponse = UpdateCredentialCredentialsCredentialIdPatchResponses[keyof UpdateCredentialCredentialsCredentialIdPatchResponses];

export type ShareCredentialCredentialsCredentialIdSharePostData = {
    body: CredentialShare;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/share';
};

export type ShareCredentialCredentialsCredentialIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareCredentialCredentialsCredentialIdSharePostError = ShareCredentialCredentialsCredentialIdSharePostErrors[keyof ShareCredentialCredentialsCredentialIdSharePostErrors];

export type ShareCredentialCredentialsCredentialIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: ApiResponseCredentialShareInfo;
};

export type ShareCredentialCredentialsCredentialIdSharePostResponse = ShareCredentialCredentialsCredentialIdSharePostResponses[keyof ShareCredentialCredentialsCredentialIdSharePostResponses];

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/share/{user_id}';
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteError = RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors[keyof RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteErrors];

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponse = RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses[keyof RevokeCredentialAccessCredentialsCredentialIdShareUserIdDeleteResponses];

export type ListCredentialSharesCredentialsCredentialIdSharesGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/shares';
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetError = ListCredentialSharesCredentialsCredentialIdSharesGetErrors[keyof ListCredentialSharesCredentialsCredentialIdSharesGetErrors];

export type ListCredentialSharesCredentialsCredentialIdSharesGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseListCredentialShareInfo;
};

export type ListCredentialSharesCredentialsCredentialIdSharesGetResponse = ListCredentialSharesCredentialsCredentialIdSharesGetResponses[keyof ListCredentialSharesCredentialsCredentialIdSharesGetResponses];

export type GetMyShareInfoCredentialsCredentialIdMyShareGetData = {
    body?: never;
    path: {
        /**
         * Credential Id
         */
        credential_id: number;
    };
    query?: never;
    url: '/credentials/{credential_id}/my-share';
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetError = GetMyShareInfoCredentialsCredentialIdMyShareGetErrors[keyof GetMyShareInfoCredentialsCredentialIdMyShareGetErrors];

export type GetMyShareInfoCredentialsCredentialIdMyShareGetResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseCredentialShareInfo;
};

export type GetMyShareInfoCredentialsCredentialIdMyShareGetResponse = GetMyShareInfoCredentialsCredentialIdMyShareGetResponses[keyof GetMyShareInfoCredentialsCredentialIdMyShareGetResponses];

export type GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostData = {
    body: GenerateWorkflowDocsRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/docs';
};

export type GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostError = GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostErrors[keyof GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostErrors];

export type GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseWorkflowDetailDocs;
};

export type GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostResponse = GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostResponses[keyof GenerateWorkflowDocsWorkflowsWorkflowIdDocsPostResponses];

export type GenerateWorkflowFromPromptWorkflowsSmithGeneratePostData = {
    body: GenerateWorkflowRequest;
    path?: never;
    query?: never;
    url: '/workflows/smith/generate';
};

export type GenerateWorkflowFromPromptWorkflowsSmithGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateWorkflowFromPromptWorkflowsSmithGeneratePostError = GenerateWorkflowFromPromptWorkflowsSmithGeneratePostErrors[keyof GenerateWorkflowFromPromptWorkflowsSmithGeneratePostErrors];

export type GenerateWorkflowFromPromptWorkflowsSmithGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: ApiResponseGeneratedWorkflow;
};

export type GenerateWorkflowFromPromptWorkflowsSmithGeneratePostResponse = GenerateWorkflowFromPromptWorkflowsSmithGeneratePostResponses[keyof GenerateWorkflowFromPromptWorkflowsSmithGeneratePostResponses];
