import type { IntegrationNodeKind, IntegrationToolMetadata } from "./types";

const INTEGRATION_ICON_BASE = "/icons/integrations";

const GMAIL_COLOR_THEME = {
  base: "hsl(5 79% 53%)",
  bg: "hsl(5 79% 53% / 0.08)",
  border: "hsl(5 79% 53% / 0.5)",
};

const SHEETS_COLOR_THEME = {
  base: "hsl(145 63% 34%)",
  bg: "hsl(145 63% 34% / 0.08)",
  border: "hsl(145 63% 34% / 0.5)",
};

const OUTLOOK_COLOR_THEME = {
  base: "hsl(207 100% 42%)",
  bg: "hsl(207 100% 42% / 0.08)",
  border: "hsl(207 100% 42% / 0.5)",
};

const JIRA_COLOR_THEME = {
  base: "hsl(215 90% 52%)",
  bg: "hsl(215 90% 52% / 0.08)",
  border: "hsl(215 90% 52% / 0.5)",
};

const SLACK_COLOR_THEME = {
  base: "hsl(285 55% 30%)",
  bg: "hsl(285 55% 30% / 0.08)",
  border: "hsl(285 55% 30% / 0.5)",
};

const GMAIL_MESSAGE_FORMAT_OPTIONS = [
  { value: "full", label: "Full" },
  { value: "metadata", label: "Metadata" },
  { value: "minimal", label: "Minimal" },
  { value: "raw", label: "Raw" },
] as const;

const VALUE_INPUT_OPTIONS = [
  { value: "USER_ENTERED", label: "User entered" },
  { value: "RAW", label: "Raw" },
] as const;

const BODY_CONTENT_TYPE_OPTIONS = [
  { value: "html", label: "HTML" },
  { value: "text", label: "Text" },
] as const;

const JIRA_API_VERSION_OPTIONS = [
  { value: "3", label: "v3 (Cloud)" },
  { value: "2", label: "v2" },
] as const;

const JIRA_BASE_ARGUMENT_FIELDS = [
  {
    name: "base_url",
    label: "Site URL",
    type: "text",
    placeholder: "https://your-domain.atlassian.net",
    help: "Required when credentials do not provide a site URL. Used to resolve the Cloud ID for OAuth.",
  },
  {
    name: "cloud_id",
    label: "Cloud ID",
    type: "text",
    placeholder: "d3c2f2e0-xxxx-xxxx-xxxx-acdeabcd1234",
    help: "Optional. Leave empty for OAuth; it will be resolved from the site URL.",
  },
  {
    name: "api_version",
    label: "API version",
    type: "select",
    options: JIRA_API_VERSION_OPTIONS,
  },
] as const;

export const INTEGRATION_TOOLS = [
  {
    kind: "integration.google.gmail.send_email",
    provider: "google",
    service: "gmail",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.gmail.read_email",
    provider: "google",
    service: "gmail",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "format",
        label: "Format",
        type: "select",
        options: GMAIL_MESSAGE_FORMAT_OPTIONS,
      },
    ],
    defaultArguments: { format: "full" },
  },
  {
    kind: "integration.google.gmail.search_emails",
    provider: "google",
    service: "gmail",
    tool: "search_emails",
    label: "Search Emails",
    description: "Search emails in Gmail using a query",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "q", label: "Search query", type: "text", required: true, placeholder: "is:unread" },
      { name: "maxResults", label: "Max results", type: "number", placeholder: "10" },
      {
        name: "labelIds",
        label: "Label IDs",
        type: "text",
        placeholder: "INBOX,UNREAD",
        help: "Comma-separated label IDs.",
      },
      { name: "includeSpamTrash", label: "Include spam and trash", type: "boolean" },
    ],
    defaultArguments: { maxResults: 10, includeSpamTrash: false },
  },
  {
    kind: "integration.google.gmail.list_labels",
    provider: "google",
    service: "gmail",
    tool: "list_labels",
    label: "List Labels",
    description: "List all Gmail labels",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.read_range",
    provider: "google",
    service: "sheets",
    tool: "read_range",
    label: "Read Range",
    description: "Read a range of cells from a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        required: true,
        placeholder: "Sheet1!A1:B10",
        help: "A1 notation. Values must match the range shape.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.write_range",
    provider: "google",
    service: "sheets",
    tool: "write_range",
    label: "Write Range",
    description: "Write data to a range of cells in a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        required: true,
        placeholder: "Sheet1!A1:B10",
        help: "A1 notation. Values must match the range shape.",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Values",
        type: "json",
        required: true,
        help: "Two-dimensional array matching the range size.",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.append_row",
    provider: "google",
    service: "sheets",
    tool: "append_row",
    label: "Append Row",
    description: "Append a row to the end of a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
        help: "The worksheet tab name to append into.",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Row values",
        type: "json",
        required: true,
        help: "A two-dimensional array for the row(s) to append.",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.update_row",
    provider: "google",
    service: "sheets",
    tool: "update_row",
    label: "Update Row",
    description: "Update a row by number",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "row_number",
        label: "Row number",
        type: "number",
        required: true,
        placeholder: "2",
      },
      {
        name: "start_column",
        label: "Start column",
        type: "text",
        required: true,
        placeholder: "A",
        help: "Column letter where your row values start (A, B, C...).",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Row values",
        type: "json",
        required: true,
        help: "Two-dimensional array with exactly one row, e.g. [[1, 2, 3]].",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.clear",
    provider: "google",
    service: "sheets",
    tool: "clear",
    label: "Clear",
    description: "Clear a sheet or a range",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        placeholder: "Sheet1",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        placeholder: "A1:D10",
        help: "If empty, clears the entire sheet.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.create_sheet",
    provider: "google",
    service: "sheets",
    tool: "create_sheet",
    label: "Create Sheet",
    description: "Create a new sheet in a spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "New Sheet",
      },
      {
        name: "rows",
        label: "Rows",
        type: "number",
        placeholder: "100",
      },
      {
        name: "columns",
        label: "Columns",
        type: "number",
        placeholder: "26",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_sheet",
    provider: "google",
    service: "sheets",
    tool: "delete_sheet",
    label: "Delete Sheet",
    description: "Delete a sheet within a spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_rows",
    provider: "google",
    service: "sheets",
    tool: "delete_rows",
    label: "Delete Rows",
    description: "Delete rows from a sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "start_row",
        label: "Start row",
        type: "number",
        required: true,
        placeholder: "2",
      },
      {
        name: "row_count",
        label: "Row count",
        type: "number",
        required: true,
        placeholder: "1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_columns",
    provider: "google",
    service: "sheets",
    tool: "delete_columns",
    label: "Delete Columns",
    description: "Delete columns from a sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "start_column",
        label: "Start column",
        type: "text",
        required: true,
        placeholder: "A",
      },
      {
        name: "column_count",
        label: "Column count",
        type: "number",
        required: true,
        placeholder: "1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.create_spreadsheet",
    provider: "google",
    service: "sheets",
    tool: "create_spreadsheet",
    label: "Create Spreadsheet",
    description: "Create a new Google Spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "New spreadsheet",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_spreadsheet",
    provider: "google",
    service: "sheets",
    tool: "delete_spreadsheet",
    label: "Delete Spreadsheet",
    description: "Delete a Google Spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.jira.issue_create",
    provider: "jira",
    service: "jira",
    tool: "issue_create",
    label: "Create Issue",
    description: "Create a Jira issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      { name: "project_key", label: "Project key", type: "text", required: true, placeholder: "PROJ" },
      { name: "issue_type", label: "Issue type", type: "text", required: true, placeholder: "Task", help: "Issue type name (e.g. Task, Bug, Story)." },
      { name: "summary", label: "Summary", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "labels", label: "Labels", type: "text", placeholder: "bug,frontend", help: "Comma-separated label names." },
      { name: "priority", label: "Priority", type: "text", placeholder: "High", help: "Priority name (e.g. High, Low, Medium)." },
      { name: "assignee_account_id", label: "Assignee account ID", type: "text", placeholder: "5b10a2844c20165700ede21g" },
      { name: "reporter_account_id", label: "Reporter account ID", type: "text", placeholder: "5b10a2844c20165700ede21g" },
      {
        name: "fields",
        label: "Fields (advanced)",
        type: "json",
        help: "Advanced: raw issue fields JSON. When provided, overrides the individual fields above on conflict.",
      },
      {
        name: "update",
        label: "Update operations",
        type: "json",
        help: "Optional update operations for fields (e.g. adding comments via the `comment` operation).",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.jira.issue_get",
    provider: "jira",
    service: "jira",
    tool: "issue_get",
    label: "Get Issue",
    description: "Get a Jira issue by ID or key",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      {
        name: "fields",
        label: "Fields to return",
        type: "text",
        placeholder: "*all",
        help: "Comma-separated field names. Use *all to return every field. Leave empty for defaults.",
      },
      {
        name: "expand",
        label: "Expand",
        type: "text",
        placeholder: "renderedFields",
        help: "Comma-separated expand options (e.g. renderedFields,names,schema).",
      },
    ],
    defaultArguments: { api_version: "3", fields: "*all" },
  },
  {
    kind: "integration.jira.issue_update",
    provider: "jira",
    service: "jira",
    tool: "issue_update",
    label: "Update Issue",
    description: "Update a Jira issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      { name: "summary", label: "Summary", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "labels", label: "Labels", type: "text", placeholder: "bug,frontend", help: "Comma-separated label names." },
      { name: "priority", label: "Priority", type: "text", placeholder: "High", help: "Priority name (e.g. High, Low, Medium)." },
      { name: "assignee_account_id", label: "Assignee account ID", type: "text", placeholder: "5b10a2844c20165700ede21g" },
      { name: "reporter_account_id", label: "Reporter account ID", type: "text", placeholder: "5b10a2844c20165700ede21g" },
      {
        name: "fields",
        label: "Fields (advanced)",
        type: "json",
        help: "Advanced: raw issue fields JSON. When provided, overrides the individual fields above on conflict.",
      },
      {
        name: "update",
        label: "Update operations",
        type: "json",
        help: "Update operations for fields (e.g. adding comments via the `comment` operation).",
      },
      {
        name: "notify_users",
        label: "Notify users",
        type: "boolean",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.jira.issue_search",
    provider: "jira",
    service: "jira",
    tool: "issue_search",
    label: "Search Issues",
    description: "Search Jira issues with JQL",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "jql",
        label: "JQL",
        type: "text",
        required: true,
        placeholder: "project = PROJ ORDER BY created DESC",
      },
      {
        name: "start_at",
        label: "Start at",
        type: "number",
        placeholder: "0",
      },
      {
        name: "max_results",
        label: "Max results",
        type: "number",
        placeholder: "50",
      },
      {
        name: "fields",
        label: "Fields to return",
        type: "text",
        placeholder: "*all",
        help: "Comma-separated field names. Use *all to return every field. Leave empty for defaults.",
      },
      {
        name: "expand",
        label: "Expand",
        type: "text",
        placeholder: "renderedFields,names,schema",
        help: "Comma-separated expand options.",
      },
      {
        name: "validate_query",
        label: "Validate query",
        type: "boolean",
      },
    ],
    defaultArguments: { api_version: "3", start_at: 0, max_results: 50, fields: "*all" },
  },
  {
    kind: "integration.jira.issue_transition_list",
    provider: "jira",
    service: "jira",
    tool: "issue_transition_list",
    label: "List Transitions",
    description: "List available transitions for an issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      {
        name: "expand",
        label: "Expand",
        type: "text",
        placeholder: "transitions.fields",
        help: "Comma-separated expand options.",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.jira.issue_transition_apply",
    provider: "jira",
    service: "jira",
    tool: "issue_transition_apply",
    label: "Apply Transition",
    description: "Apply a transition to an issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      {
        name: "transition_id",
        label: "Transition ID",
        type: "text",
        placeholder: "31",
      },
      {
        name: "transition",
        label: "Transition",
        type: "json",
        help: "Optional transition object payload.",
      },
      {
        name: "fields",
        label: "Fields",
        type: "json",
        help: "Fields to set during the transition.",
      },
      {
        name: "update",
        label: "Update",
        type: "json",
        help: "Optional update operations for fields.",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.jira.comment_create",
    provider: "jira",
    service: "jira",
    tool: "comment_create",
    label: "Create Comment",
    description: "Add a comment to a Jira issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      {
        name: "text_body",
        label: "Comment text",
        type: "textarea",
        help: "Plain text comment. Leave empty if using the JSON Body field below.",
      },
      {
        name: "body",
        label: "Body (advanced)",
        type: "json",
        help: "Advanced: Atlassian Document Format JSON body. Leave empty when using plain text above.",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.jira.comment_list",
    provider: "jira",
    service: "jira",
    tool: "comment_list",
    label: "List Comments",
    description: "List comments for a Jira issue",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "issue_id_or_key",
        label: "Issue ID or key",
        type: "text",
        required: true,
        placeholder: "PROJ-123",
      },
      {
        name: "start_at",
        label: "Start at",
        type: "number",
        placeholder: "0",
      },
      {
        name: "max_results",
        label: "Max results",
        type: "number",
        placeholder: "50",
      },
      {
        name: "order_by",
        label: "Order by",
        type: "text",
        placeholder: "created",
      },
      {
        name: "expand",
        label: "Expand",
        type: "text",
        placeholder: "renderedBody",
      },
    ],
    defaultArguments: { api_version: "3", start_at: 0 },
  },
  {
    kind: "integration.jira.project_list",
    provider: "jira",
    service: "jira",
    tool: "project_list",
    label: "List Projects",
    description: "List Jira projects",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "start_at",
        label: "Start at",
        type: "number",
        placeholder: "0",
      },
      {
        name: "max_results",
        label: "Max results",
        type: "number",
        placeholder: "50",
      },
    ],
    defaultArguments: { api_version: "3", start_at: 0 },
  },
  {
    kind: "integration.jira.user_get",
    provider: "jira",
    service: "jira",
    tool: "user_get",
    label: "Get User",
    description: "Get a Jira user",
    providerLabel: "Jira",
    serviceLabel: "Jira",
    icon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/jira.svg`,
    colorTheme: JIRA_COLOR_THEME,
    argumentFields: [
      ...JIRA_BASE_ARGUMENT_FIELDS,
      {
        name: "query",
        label: "Search by name or email",
        type: "text",
        placeholder: "john@example.com",
        help: "Search for users to find their account ID. Leave empty to look up by exact account ID instead.",
      },
      {
        name: "account_id",
        label: "Account ID (exact lookup)",
        type: "text",
        placeholder: "5b10a2844c20165700ede21g",
        help: "Only used when Search query is empty. Required for API v3 exact lookup.",
      },
      {
        name: "username",
        label: "Username (v2 exact lookup)",
        type: "text",
        help: "Use with API v2 when search query and account ID are not available.",
      },
      {
        name: "user_key",
        label: "User key (v2 exact lookup)",
        type: "text",
        help: "Use with API v2 when search query and account ID are not available.",
      },
    ],
    defaultArguments: { api_version: "3" },
  },
  {
    kind: "integration.microsoft.outlook.send_email",
    provider: "microsoft",
    service: "outlook",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Microsoft Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "save_to_sent_items", label: "Save to Sent Items", type: "boolean" },
    ],
    defaultArguments: { save_to_sent_items: true },
  },
  {
    kind: "integration.microsoft.outlook.read_email",
    provider: "microsoft",
    service: "outlook",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "select",
        label: "Select fields",
        type: "text",
        placeholder: "subject,from,bodyPreview",
        help: "Comma-separated list of fields to return.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.microsoft.outlook.search_emails",
    provider: "microsoft",
    service: "outlook",
    tool: "search_emails",
    label: "Search Emails",
    description: "Search emails in Outlook using a query",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "q", label: "Search query", type: "text", placeholder: "meeting" },
      { name: "labelIds", label: "Folder ID", type: "text", placeholder: "inbox" },
      { name: "maxResults", label: "Max results", type: "number", placeholder: "10" },
    ],
    defaultArguments: { maxResults: 10 },
  },
  {
    kind: "integration.microsoft.outlook.list_folders",
    provider: "microsoft",
    service: "outlook",
    tool: "list_folders",
    label: "List Folders",
    description: "List all Outlook mail folders",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.post_message",
    provider: "slack",
    service: "slack",
    tool: "post_message",
    label: "Send Message",
    description: "Send a message to a Slack channel",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      {
        name: "channel",
        label: "Channel or User ID",
        type: "text",
        required: true,
        placeholder: "C123... or U123...",
      },
      { name: "text", label: "Message", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.update",
    provider: "slack",
    service: "slack",
    tool: "update_message",
    label: "Update Message",
    description: "Update an existing Slack message",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "ts", label: "Message Timestamp", type: "text", required: true },
      { name: "text", label: "New Message", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.delete",
    provider: "slack",
    service: "slack",
    tool: "delete_message",
    label: "Delete Message",
    description: "Delete a Slack message",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "ts", label: "Message Timestamp", type: "text", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.conversations.history",
    provider: "slack",
    service: "slack",
    tool: "read_history",
    label: "Read Channel History",
    description: "Read recent messages from a channel",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "limit", label: "Max messages", type: "number", placeholder: "10" },
    ],
    defaultArguments: { limit: 10 },
  },
  {
    kind: "integration.slack.conversations.find_message",
    provider: "slack",
    service: "slack",
    tool: "find_message",
    label: "Find Message",
    description: "Search recent messages in a channel for a specific keyword",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "keyword", label: "Keyword", type: "text", required: true, placeholder: "Error 500" },
      { name: "limit", label: "Messages to search", type: "number", placeholder: "100" },
    ],
    defaultArguments: { limit: 100 },
  },
  {
    kind: "integration.slack.users.lookup_by_email",
    provider: "slack",
    service: "slack",
    tool: "lookup_by_email",
    label: "Lookup by Email",
    description: "Find a Slack User ID using their email address",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      {
        name: "email",
        label: "Email Address",
        type: "text",
        required: true,
        placeholder: "jane@example.com",
      },
    ],
    defaultArguments: {},
  },
] as const satisfies readonly IntegrationToolMetadata[];

export const INTEGRATION_NODE_KINDS = INTEGRATION_TOOLS.map((tool) => tool.kind);

export const INTEGRATION_TOOL_BY_KIND = Object.fromEntries(
  INTEGRATION_TOOLS.map((tool) => [tool.kind, tool]),
) as unknown as Record<IntegrationNodeKind, IntegrationToolMetadata>;
