import type { IntegrationNodeKind, IntegrationToolMetadata } from "./types";

const INTEGRATION_ICON_BASE = "/icons/integrations";

const GMAIL_COLOR_THEME = {
  base: "hsl(5 79% 53%)",
  bg: "hsl(5 79% 53% / 0.08)",
  border: "hsl(5 79% 53% / 0.5)",
};

const SHEETS_COLOR_THEME = {
  base: "hsl(145 63% 34%)",
  bg: "hsl(145 63% 34% / 0.08)",
  border: "hsl(145 63% 34% / 0.5)",
};

const OUTLOOK_COLOR_THEME = {
  base: "hsl(207 100% 42%)",
  bg: "hsl(207 100% 42% / 0.08)",
  border: "hsl(207 100% 42% / 0.5)",
};

const GMAIL_MESSAGE_FORMAT_OPTIONS = [
  { value: "full", label: "Full" },
  { value: "metadata", label: "Metadata" },
  { value: "minimal", label: "Minimal" },
  { value: "raw", label: "Raw" },
] as const;

const VALUE_INPUT_OPTIONS = [
  { value: "USER_ENTERED", label: "User entered" },
  { value: "RAW", label: "Raw" },
] as const;

const BODY_CONTENT_TYPE_OPTIONS = [
  { value: "html", label: "HTML" },
  { value: "text", label: "Text" },
] as const;

export const INTEGRATION_TOOLS = [
  {
    kind: "integration.google.gmail.send_email",
    provider: "google",
    service: "gmail",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.gmail.read_email",
    provider: "google",
    service: "gmail",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "format",
        label: "Format",
        type: "select",
        options: GMAIL_MESSAGE_FORMAT_OPTIONS,
      },
    ],
    defaultArguments: { format: "full" },
  },
  {
    kind: "integration.google.gmail.search_emails",
    provider: "google",
    service: "gmail",
    tool: "search_emails",
    label: "Search Emails",
    description: "Search emails in Gmail using a query",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "q", label: "Search query", type: "text", required: true, placeholder: "is:unread" },
      { name: "maxResults", label: "Max results", type: "number", placeholder: "10" },
      {
        name: "labelIds",
        label: "Label IDs",
        type: "text",
        placeholder: "INBOX,UNREAD",
        help: "Comma-separated label IDs.",
      },
      { name: "includeSpamTrash", label: "Include spam and trash", type: "boolean" },
    ],
    defaultArguments: { maxResults: 10, includeSpamTrash: false },
  },
  {
    kind: "integration.google.gmail.list_labels",
    provider: "google",
    service: "gmail",
    tool: "list_labels",
    label: "List Labels",
    description: "List all Gmail labels",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.read_range",
    provider: "google",
    service: "sheets",
    tool: "read_range",
    label: "Read Range",
    description: "Read a range of cells from a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      { name: "spreadsheet_id", label: "Spreadsheet ID", type: "text", required: true },
      { name: "range", label: "Range", type: "text", required: true, placeholder: "Sheet1!A1:B10" },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.write_range",
    provider: "google",
    service: "sheets",
    tool: "write_range",
    label: "Write Range",
    description: "Write data to a range of cells in a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      { name: "spreadsheet_id", label: "Spreadsheet ID", type: "text", required: true },
      { name: "range", label: "Range", type: "text", required: true, placeholder: "Sheet1!A1:B10" },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Values",
        type: "json",
        required: true,
        help: 'A two-dimensional array, for example [["Name", "Status"]].',
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.append_row",
    provider: "google",
    service: "sheets",
    tool: "append_row",
    label: "Append Row",
    description: "Append a row to the end of a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      { name: "spreadsheet_id", label: "Spreadsheet ID", type: "text", required: true },
      {
        name: "range",
        label: "Table range",
        type: "text",
        required: true,
        placeholder: "Sheet1!A1:D",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Row values",
        type: "json",
        required: true,
        help: "A two-dimensional array for the row(s) to append.",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.create_spreadsheet",
    provider: "google",
    service: "sheets",
    tool: "create_spreadsheet",
    label: "Create Spreadsheet",
    description: "Create a new Google Spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "New spreadsheet",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.microsoft.outlook.send_email",
    provider: "microsoft",
    service: "outlook",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Microsoft Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "save_to_sent_items", label: "Save to Sent Items", type: "boolean" },
    ],
    defaultArguments: { save_to_sent_items: true },
  },
  {
    kind: "integration.microsoft.outlook.read_email",
    provider: "microsoft",
    service: "outlook",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "select",
        label: "Select fields",
        type: "text",
        placeholder: "subject,from,bodyPreview",
      },
      {
        name: "body_content_type",
        label: "Body format",
        type: "select",
        options: BODY_CONTENT_TYPE_OPTIONS,
      },
    ],
    defaultArguments: { body_content_type: "html" },
  },
  {
    kind: "integration.microsoft.outlook.list_inbox",
    provider: "microsoft",
    service: "outlook",
    tool: "list_inbox",
    label: "List Inbox",
    description: "List recent emails from Outlook inbox",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "top", label: "Max results", type: "number", placeholder: "10" },
      { name: "search", label: "Search", type: "text", placeholder: "subject:report" },
      {
        name: "select",
        label: "Select fields",
        type: "text",
        placeholder: "subject,from,receivedDateTime",
      },
      {
        name: "body_content_type",
        label: "Body format",
        type: "select",
        options: BODY_CONTENT_TYPE_OPTIONS,
      },
    ],
    defaultArguments: { top: 10, body_content_type: "html" },
  },
] as const satisfies readonly IntegrationToolMetadata[];

export const INTEGRATION_NODE_KINDS = INTEGRATION_TOOLS.map((tool) => tool.kind);

export const INTEGRATION_TOOL_BY_KIND = Object.fromEntries(
  INTEGRATION_TOOLS.map((tool) => [tool.kind, tool]),
) as unknown as Record<IntegrationNodeKind, IntegrationToolMetadata>;
