import type { IntegrationNodeKind, IntegrationToolMetadata } from "./types";

const INTEGRATION_ICON_BASE = "/icons/integrations";

const GMAIL_COLOR_THEME = {
  base: "hsl(5 79% 53%)",
  bg: "hsl(5 79% 53% / 0.08)",
  border: "hsl(5 79% 53% / 0.5)",
};

const SHEETS_COLOR_THEME = {
  base: "hsl(145 63% 34%)",
  bg: "hsl(145 63% 34% / 0.08)",
  border: "hsl(145 63% 34% / 0.5)",
};

const OUTLOOK_COLOR_THEME = {
  base: "hsl(207 100% 42%)",
  bg: "hsl(207 100% 42% / 0.08)",
  border: "hsl(207 100% 42% / 0.5)",
};

const SLACK_COLOR_THEME = {
  base: "hsl(285 55% 30%)",
  bg: "hsl(285 55% 30% / 0.08)",
  border: "hsl(285 55% 30% / 0.5)",
};

const DROPBOX_COLOR_THEME = {
  base: "hsl(217 100% 50%)",
  bg: "hsl(217 100% 50% / 0.08)",
  border: "hsl(217 100% 50% / 0.5)",
};

const GMAIL_MESSAGE_FORMAT_OPTIONS = [
  { value: "full", label: "Full" },
  { value: "metadata", label: "Metadata" },
  { value: "minimal", label: "Minimal" },
  { value: "raw", label: "Raw" },
] as const;

const VALUE_INPUT_OPTIONS = [
  { value: "USER_ENTERED", label: "User entered" },
  { value: "RAW", label: "Raw" },
] as const;

const BODY_CONTENT_TYPE_OPTIONS = [
  { value: "html", label: "HTML" },
  { value: "text", label: "Text" },
] as const;

export const INTEGRATION_TOOLS = [
  {
    kind: "integration.google.gmail.send_email",
    provider: "google",
    service: "gmail",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.gmail.read_email",
    provider: "google",
    service: "gmail",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Gmail",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "format",
        label: "Format",
        type: "select",
        options: GMAIL_MESSAGE_FORMAT_OPTIONS,
      },
    ],
    defaultArguments: { format: "full" },
  },
  {
    kind: "integration.google.gmail.search_emails",
    provider: "google",
    service: "gmail",
    tool: "search_emails",
    label: "Search Emails",
    description: "Search emails in Gmail using a query",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [
      { name: "q", label: "Search query", type: "text", required: true, placeholder: "is:unread" },
      { name: "maxResults", label: "Max results", type: "number", placeholder: "10" },
      {
        name: "labelIds",
        label: "Label IDs",
        type: "text",
        placeholder: "INBOX,UNREAD",
        help: "Comma-separated label IDs.",
      },
      { name: "includeSpamTrash", label: "Include spam and trash", type: "boolean" },
    ],
    defaultArguments: { maxResults: 10, includeSpamTrash: false },
  },
  {
    kind: "integration.google.gmail.list_labels",
    provider: "google",
    service: "gmail",
    tool: "list_labels",
    label: "List Labels",
    description: "List all Gmail labels",
    providerLabel: "Google",
    serviceLabel: "Gmail",
    icon: `${INTEGRATION_ICON_BASE}/google-gmail.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: GMAIL_COLOR_THEME,
    argumentFields: [],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.read_range",
    provider: "google",
    service: "sheets",
    tool: "read_range",
    label: "Read Range",
    description: "Read a range of cells from a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        required: true,
        placeholder: "Sheet1!A1:B10",
        help: "A1 notation. Values must match the range shape.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.write_range",
    provider: "google",
    service: "sheets",
    tool: "write_range",
    label: "Write Range",
    description: "Write data to a range of cells in a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        required: true,
        placeholder: "Sheet1!A1:B10",
        help: "A1 notation. Values must match the range shape.",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Values",
        type: "json",
        required: true,
        help: "Two-dimensional array matching the range size.",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.append_row",
    provider: "google",
    service: "sheets",
    tool: "append_row",
    label: "Append Row",
    description: "Append a row to the end of a Google Sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
        help: "The worksheet tab name to append into.",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Row values",
        type: "json",
        required: true,
        help: "A two-dimensional array for the row(s) to append.",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.update_row",
    provider: "google",
    service: "sheets",
    tool: "update_row",
    label: "Update Row",
    description: "Update a row by number",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "row_number",
        label: "Row number",
        type: "number",
        required: true,
        placeholder: "2",
      },
      {
        name: "start_column",
        label: "Start column",
        type: "text",
        required: true,
        placeholder: "A",
        help: "Column letter where your row values start (A, B, C...).",
      },
      {
        name: "value_input_option",
        label: "Value input",
        type: "select",
        options: VALUE_INPUT_OPTIONS,
      },
      {
        name: "values",
        label: "Row values",
        type: "json",
        required: true,
        help: "Two-dimensional array with exactly one row, e.g. [[1, 2, 3]].",
      },
    ],
    defaultArguments: { value_input_option: "USER_ENTERED", values: [[]] },
  },
  {
    kind: "integration.google.sheets.clear",
    provider: "google",
    service: "sheets",
    tool: "clear",
    label: "Clear",
    description: "Clear a sheet or a range",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        placeholder: "Sheet1",
      },
      {
        name: "range",
        label: "Range",
        type: "text",
        placeholder: "A1:D10",
        help: "If empty, clears the entire sheet.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.create_sheet",
    provider: "google",
    service: "sheets",
    tool: "create_sheet",
    label: "Create Sheet",
    description: "Create a new sheet in a spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "New Sheet",
      },
      {
        name: "rows",
        label: "Rows",
        type: "number",
        placeholder: "100",
      },
      {
        name: "columns",
        label: "Columns",
        type: "number",
        placeholder: "26",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_sheet",
    provider: "google",
    service: "sheets",
    tool: "delete_sheet",
    label: "Delete Sheet",
    description: "Delete a sheet within a spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_rows",
    provider: "google",
    service: "sheets",
    tool: "delete_rows",
    label: "Delete Rows",
    description: "Delete rows from a sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "start_row",
        label: "Start row",
        type: "number",
        required: true,
        placeholder: "2",
      },
      {
        name: "row_count",
        label: "Row count",
        type: "number",
        required: true,
        placeholder: "1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_columns",
    provider: "google",
    service: "sheets",
    tool: "delete_columns",
    label: "Delete Columns",
    description: "Delete columns from a sheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
      {
        name: "sheet_name",
        label: "Sheet name",
        type: "text",
        required: true,
        placeholder: "Sheet1",
      },
      {
        name: "start_column",
        label: "Start column",
        type: "text",
        required: true,
        placeholder: "A",
      },
      {
        name: "column_count",
        label: "Column count",
        type: "number",
        required: true,
        placeholder: "1",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.create_spreadsheet",
    provider: "google",
    service: "sheets",
    tool: "create_spreadsheet",
    label: "Create Spreadsheet",
    description: "Create a new Google Spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        placeholder: "New spreadsheet",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.google.sheets.delete_spreadsheet",
    provider: "google",
    service: "sheets",
    tool: "delete_spreadsheet",
    label: "Delete Spreadsheet",
    description: "Delete a Google Spreadsheet",
    providerLabel: "Google",
    serviceLabel: "Google Sheets",
    icon: `${INTEGRATION_ICON_BASE}/google-sheets.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/google.svg`,
    colorTheme: SHEETS_COLOR_THEME,
    argumentFields: [
      {
        name: "spreadsheet_id",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        help: "From the URL: https://docs.google.com/spreadsheets/d/<id>/edit",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.microsoft.outlook.send_email",
    provider: "microsoft",
    service: "outlook",
    tool: "send_email",
    label: "Send Email",
    description: "Send an email via Microsoft Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "to", label: "To", type: "text", required: true, placeholder: "team@example.com" },
      { name: "cc", label: "Cc", type: "text", placeholder: "cc@example.com" },
      { name: "bcc", label: "Bcc", type: "text", placeholder: "bcc@example.com" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "save_to_sent_items", label: "Save to Sent Items", type: "boolean" },
    ],
    defaultArguments: { save_to_sent_items: true },
  },
  {
    kind: "integration.microsoft.outlook.read_email",
    provider: "microsoft",
    service: "outlook",
    tool: "read_email",
    label: "Read Email",
    description: "Read an email by ID from Outlook",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "id", label: "Message ID", type: "text", required: true },
      {
        name: "select",
        label: "Select fields",
        type: "text",
        placeholder: "subject,from,bodyPreview",
        help: "Comma-separated list of fields to return.",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.microsoft.outlook.search_emails",
    provider: "microsoft",
    service: "outlook",
    tool: "search_emails",
    label: "Search Emails",
    description: "Search emails in Outlook using a query",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [
      { name: "q", label: "Search query", type: "text", placeholder: "meeting" },
      { name: "labelIds", label: "Folder ID", type: "text", placeholder: "inbox" },
      { name: "maxResults", label: "Max results", type: "number", placeholder: "10" },
    ],
    defaultArguments: { maxResults: 10 },
  },
  {
    kind: "integration.microsoft.outlook.list_folders",
    provider: "microsoft",
    service: "outlook",
    tool: "list_folders",
    label: "List Folders",
    description: "List all Outlook mail folders",
    providerLabel: "Microsoft",
    serviceLabel: "Outlook",
    icon: `${INTEGRATION_ICON_BASE}/microsoft-outlook.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/microsoft.svg`,
    colorTheme: OUTLOOK_COLOR_THEME,
    argumentFields: [],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.post_message",
    provider: "slack",
    service: "slack",
    tool: "post_message",
    label: "Send Message",
    description: "Send a message to a Slack channel",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      {
        name: "channel",
        label: "Channel or User ID",
        type: "text",
        required: true,
        placeholder: "C123... or U123...",
      },
      { name: "text", label: "Message", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.update",
    provider: "slack",
    service: "slack",
    tool: "update_message",
    label: "Update Message",
    description: "Update an existing Slack message",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "ts", label: "Message Timestamp", type: "text", required: true },
      { name: "text", label: "New Message", type: "textarea", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.chat.delete",
    provider: "slack",
    service: "slack",
    tool: "delete_message",
    label: "Delete Message",
    description: "Delete a Slack message",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "ts", label: "Message Timestamp", type: "text", required: true },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.slack.conversations.history",
    provider: "slack",
    service: "slack",
    tool: "read_history",
    label: "Read Channel History",
    description: "Read recent messages from a channel",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "limit", label: "Max messages", type: "number", placeholder: "10" },
    ],
    defaultArguments: { limit: 10 },
  },
  {
    kind: "integration.slack.conversations.find_message",
    provider: "slack",
    service: "slack",
    tool: "find_message",
    label: "Find Message",
    description: "Search recent messages in a channel for a specific keyword",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      { name: "channel", label: "Channel or User ID", type: "text", required: true },
      { name: "keyword", label: "Keyword", type: "text", required: true, placeholder: "Error 500" },
      { name: "limit", label: "Messages to search", type: "number", placeholder: "100" },
    ],
    defaultArguments: { limit: 100 },
  },
  {
    kind: "integration.slack.users.lookup_by_email",
    provider: "slack",
    service: "slack",
    tool: "lookup_by_email",
    label: "Lookup by Email",
    description: "Find a Slack User ID using their email address",
    providerLabel: "Slack",
    serviceLabel: "Slack",
    icon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/slack.svg`,
    colorTheme: SLACK_COLOR_THEME,
    argumentFields: [
      {
        name: "email",
        label: "Email Address",
        type: "text",
        required: true,
        placeholder: "jane@example.com",
      },
    ],
    defaultArguments: {},
  },
  {
    kind: "integration.dropbox.files.list_folder",
    provider: "dropbox",
    service: "dropbox",
    tool: "list_folder",
    label: "List Folder",
    description: "List files and subfolders in a Dropbox directory",
    providerLabel: "Dropbox",
    serviceLabel: "Dropbox",
    icon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    colorTheme: DROPBOX_COLOR_THEME,
    argumentFields: [
      {
        name: "path",
        label: "Folder Path",
        type: "text",
        required: false,
        placeholder: "/Documents or leave empty for root",
        help: "The path to the folder you want to list. Use empty string for the root folder.",
      },
      {
        name: "recursive",
        label: "Recursive",
        type: "boolean",
        help: "If true, the list will include all subfolders and files recursively.",
      },
      {
        name: "limit",
        label: "Max Results",
        type: "number",
        placeholder: "100",
        help: "Maximum number of results to return.",
      },
    ],
    defaultArguments: { path: "", recursive: false, limit: 100 },
  },
  {
    kind: "integration.dropbox.files.get_metadata",
    provider: "dropbox",
    service: "dropbox",
    tool: "get_metadata",
    label: "Get Metadata",
    description: "Get metadata for a file or folder in Dropbox",
    providerLabel: "Dropbox",
    serviceLabel: "Dropbox",
    icon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    colorTheme: DROPBOX_COLOR_THEME,
    argumentFields: [
      {
        name: "path",
        label: "Path or ID",
        type: "text",
        required: true,
        placeholder: "/Documents/report.pdf or file id",
        help: "The path or ID of the file or folder.",
      },
    ],
    defaultArguments: { path: "" },
  },
  {
    kind: "integration.dropbox.files.get_temporary_link",
    provider: "dropbox",
    service: "dropbox",
    tool: "get_temporary_link",
    label: "Get Temporary Link",
    description: "Get a temporary download link for a file in Dropbox",
    providerLabel: "Dropbox",
    serviceLabel: "Dropbox",
    icon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    colorTheme: DROPBOX_COLOR_THEME,
    argumentFields: [
      {
        name: "path",
        label: "File Path",
        type: "text",
        required: true,
        placeholder: "/Documents/report.pdf",
        help: "The path to the file you want to download.",
      },
    ],
    defaultArguments: { path: "" },
  },
  {
    kind: "integration.dropbox.files.delete",
    provider: "dropbox",
    service: "dropbox",
    tool: "delete",
    label: "Delete File or Folder",
    description: "Delete a file or folder in Dropbox",
    providerLabel: "Dropbox",
    serviceLabel: "Dropbox",
    icon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    colorTheme: DROPBOX_COLOR_THEME,
    argumentFields: [
      {
        name: "path",
        label: "Path or ID",
        type: "text",
        required: true,
        placeholder: "/Documents/report.pdf",
        help: "The path or ID of the file or folder to delete.",
      },
    ],
    defaultArguments: { path: "" },
  },
  {
    kind: "integration.dropbox.files.search",
    provider: "dropbox",
    service: "dropbox",
    tool: "search",
    label: "Search Files",
    description: "Search for files by name/query in Dropbox",
    providerLabel: "Dropbox",
    serviceLabel: "Dropbox",
    icon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    providerIcon: `${INTEGRATION_ICON_BASE}/dropbox.svg`,
    colorTheme: DROPBOX_COLOR_THEME,
    argumentFields: [
      {
        name: "query",
        label: "Search Query / File Name",
        type: "text",
        required: true,
        placeholder: "report.pdf",
        help: "The search string or file name to look for.",
      },
      {
        name: "path",
        label: "Search Path",
        type: "text",
        required: false,
        placeholder: "/Documents or leave empty for root",
        help: "Limit search to this folder path. If empty, searches the entire Dropbox.",
      },
      {
        name: "filename_only",
        label: "Filename Only",
        type: "boolean",
        help: "If true, search only matches the file names, not content or descriptions.",
      },
    ],
    defaultArguments: { query: "", path: "", filename_only: true },
  },
] as const satisfies readonly IntegrationToolMetadata[];

export const INTEGRATION_NODE_KINDS = INTEGRATION_TOOLS.map((tool) => tool.kind);

export const INTEGRATION_TOOL_BY_KIND = Object.fromEntries(
  INTEGRATION_TOOLS.map((tool) => [tool.kind, tool]),
) as unknown as Record<IntegrationNodeKind, IntegrationToolMetadata>;
